### ISSUE TITLE
bib 里 inproceedings 的处理不对

### ISSUE THREAD

**Issue by grissiom** [BHOSC/BUAAthesis#115]
应该是 title[A]. booktitle[C]。bst 处理成了 tile[C]//booktitle 的格式……

**Comment by daibluewater** [comment]
KagamiChan提供的那个bst编译是没有问题的，而且写的整齐一些。这里提供的bst编译以后提示说好多函数找不到。

**Comment by zepinglee** [comment]
可以使用 https://github.com/zepinglee/gbt7714-bibtex-style 或 
https://github.com/hushidong/biblatex-gb7714-2015

**Comment by huxuan** [comment]
Closed as bst upgraded. Please feel free to reopen it if there is still any similar issue.
