### ISSUE TITLE
使用 algorithm+algorithmic 包出错

### ISSUE THREAD

**Issue by yuhuazou** [BHOSC/BUAAthesis#129]
使用 algorithm+algorithmic 包写算法步骤时出错，会出现 Command \LOOP already defined 的错误，使用 \savesymbol 指令把 \LOOP 和 \REPEAT 保存后这个错误没有了，但会出现 \Require undefined 的错误。

测试代码：

% !Mode:: "TeX:UTF-8"
\documentclass[doctor,openright,twoside,color]{buaathesis} % for pdf version

\usepackage{mathdots}
\savesymbol{LOOP}
\savesymbol{REPEAT}
\usepackage{algorithm}
\usepackage{algorithmic}
\floatname{algorithm}{Algorithm}
\renewcommand{\algorithmicrequire}{\textbf{输入:}}  % Use Input in the format of Algorithm
\renewcommand{\algorithmicensure}{\textbf{输出:}} % Use Output in the format of Algorithm

\begin{document}

% 用户信息
\include{data/com_info}
\include{data/master/master_info}

% 中英封面、提名页、授权书
\maketitle
% 前言页眉页脚样式
\pagestyle{frontmatter}
% 摘要
\include{data/abstract}
% 目录、插图目录、表格目录
\tableofcontents
\listoffigures
\listoftables
% 符号表
\include{data/master/denotation}

% 正文页码样式
\mainmatter
% 正文页眉页脚样式
\pagestyle{mainmatter}

% 正文
\begin{algorithm}[h]
  \caption{图优化(高斯牛顿法)}
  \label{alg:graph_opt}
  \begin{algorithmic}[1] %这个1 表示每一行都显示数字
    \Require
      待估状态初值$V^{0}=\{x_{i}^{0}\}$；
      边集合$E=\{(i,j)\}$；
      每条边所对应的观测方程$h_{ij}$；
      观测量$z_{ij}$和方差$\Sigma_{ij}$.
    \Ensure
      $V$的最优估计$V^{*}$.
    \State 设$\bar{V}=\{\bar{x}_{i}\}$为当前解；
    \State 设$H$为Hessian矩阵；$H_{[ij]}$为$H$第$i$行第$j$列的分块；
    \State $b$为右端项；$b_{[i]}$为$b$中对应于顶点$x_{i}$的向量；
    \While {尚未收敛}
      \For{$(i,j) \in E$}
        \State $//$增量构建$H$和$b$；
        \State $A_{ij}:=\frac{\partial h_{ij}(x_{i},x_{j})}{\partial x_{i}}\big|_{\bar{x}_{i}},\: B_{ij}:=\frac{\partial h_{ij}(x_{i},x_{j})}{\partial x_{i}}\big|_{\bar{x}_{i}};$
        \State $H_{[ii]}+=A_{ij}^{T}\Omega_{ij}A_{ij};\: H_{[ij]}+=A_{ij}^{T}\Omega_{ij}B_{ij};$
        \State $H_{[ji]}+=B_{ij}^{T}\Omega_{ij}A_{ij};\: H_{[jj]}+=B_{ij}^{T}\Omega_{ij}B_{ij};$
        \State $b_{[i]}+=A_{ij}^{T}\Omega_{ij}e_{ij};\: b_{[j]}+=B_{ij}^{T}\Omega_{ij}e_{ij}$
      \EndFor
      \State $H_{[11]}+=I;\quad$ $//$固定第一个顶点
      \State $\delta:=solve(H\delta=-b)$;
      \State $x+=\delta;$
    \EndWhile
    \State $x^{*}:=\bar{x};\: H^{*}:=H;$
    \State $H_{[11]}^{*}-=I;\quad$ $//$释放第一个顶点
    \Return $(x^{*},H^{*});$}$H^{*}$;
  \end{algorithmic}
\end{algorithm}

% 参考文献
\include{data/reference}

% 附录
%\appendix
%\include{data/appendix1-faq}
%\include{data/appendix2-contactus}

% 附页标题样式
\backmatter

% 附页
\include{data/master/back1-achievement}
\include{data/master/back2-thanks}
\include{data/master/back3-aboutauthor}
\end{document}

**Comment by huxuan** [comment]
Close as problem solved.
