### ISSUE TITLE
BUG: 指导教师名字不居中

### ISSUE THREAD

**Issue by luohancfd** [BHOSC/BUAAthesis#146]
位置：buaathesis.cls  497行
详情：\buaa@teacher和\buaa@subteacher中间的\quad会造成当不存在\buaa@subteacher时，\buaa@teacher后面空出一个格，编译出的pdf文件指导教师的姓名不居中，建议根据\buaa@subteacher的值是否存在来决定是否要加\quad

**Comment by BiggerHao** [comment]
但是我没有subteacher，导师姓名也是不能居中啊 😢

**Comment by huxuan** [comment]
Please provide more specific information so we can reproduce your problem and offer potential help.

**Comment by BiggerHao** [comment]
@huxuan 导师姓名往左偏了一点点，不是正好居中的，我用的是本科毕业论文的tex文件生成的pdf

**Comment by huxuan** [comment]
@BiggerHao Please point out the specific place as there are many places that contain teacher names. It is better to provide a screenshot and related code snippets. The more specific the better.

**Comment by BiggerHao** [comment]
@huxuan 
com_info.tex
![2017-04-28 2 30 15](https://cloud.githubusercontent.com/assets/7645930/25516871/6061fac8-2c1f-11e7-99b9-4965ee9b7871.png)
sample-bachelor.pdf
![2017-04-28 2 30 33](https://cloud.githubusercontent.com/assets/7645930/25516895/79d63032-2c1f-11e7-8a04-7675783627b8.png)

**Comment by huxuan** [comment]
It seems to be a bug here [1]. Just reopen the issue for tracking.

[1] https://github.com/BHOSC/BUAAthesis/blo/master/buaathesis.cls#L541

**Comment by huxuan** [comment]
@BiggerHao Can you help me to verify whether the cls file here [1] fix this bug? I do not have TeX environment right now cause I have been graduated for years. :-)

[1] https://github.com/huxuan/BUAAthesis/blob/bachelor-subteacher-bug/buaathesis.cls

**Comment by BiggerHao** [comment]
@huxuan That fixes the bug. Thanks.
