### ISSUE TITLE
参考文献里好多 .[S.l.]: [s.n.] 

### ISSUE THREAD

**Issue by songjinghe** [BHOSC/BUAAthesis#155]
我下载了最新的模板编译后还是有这个问题。。。。
我用的是texlive2013
详见：https://github.com/BHOSC/BUAAthesis/issues/115#issuecomment-45571540

**Comment by hengshanji** [comment]
应该用texlive2015 这样应该就没有问题了，我也是今年的毕业生，必须用2015版的

**Comment by huxuan** [comment]
@hengshanji 谢谢你的反馈确认~

**Comment by lijinfeng0713** [comment]
![image](https://user-images.githubusercontent.com/9656113/68177266-ba8c3580-ffc2-11e9-99d2-9e578022cda2.png)
设置gbpub=false即可忽略出版社和出版地信息

**Comment by BiggerHao** [comment]
@lijinfeng0713 请问能否提供更多的信息呢？我把这句加到\begin{document}前面会报错。请问是否还进行了其他修改？

**Comment by BiggerHao** [comment]
终于解决了:rofl: 参考上面使用biblatex，具体步骤为：
- 注释掉`buaathesis.cls`的下面几行：
````
% \bibliographystyle{buaathesis} % 参考文献格式
% \RequirePackage[sort&compress]{natbib}
% \bibpunct{[}{]}{,}{n}{}{}
% \setlength{\bibsep}{0pt}
````
- 在tex主文件里的`\begin{document}`之间添加：（其中bibs.bib是你的bib文件名，biblatex选项也可以进行其他的设置，可参考https://github.com/hushidong/biblatex-gb7714-2015）
````
\usepackage[backend=biber,style=numeric,sorting=none,gbpub=false,bibstyle=gb7714-2015,citestyle=gb7714-2015]{biblatex}
\addbibresource[location=local]{data/bibs.bib}
````
- 在`reference.tex`里注释掉下面的第一行，并添加第二行：
````
% \bibliography{data/bibs}
\printbibliography
````
- 若使用TeXStudio，在选项-设置-构建里，设置默认文献工具为Biber，若使用其他IDE应该也要进行相应的修改。

**Comment by meteorsh** [comment]
![image](https://user-images.githubusercontent.com/46078304/80913126-d8213880-8d74-11ea-8319-3ca525a7e6ef.png)

请问下红色箭头处的//要怎么去掉？

**Comment by JasonHans** [comment]
> ![image](https://user-images.githubusercontent.com/9656113/68177266-ba8c3580-ffc2-11e9-99d2-9e578022cda2.png) 设置gbpub=false即可忽略出版社和出版地信息

这是在哪个文件里的什么位置修改呢？找遍了，也没找到

**Comment by h4yk3r** [comment]
给后来的同学总结一下，目前是2022/5/7，按照@BiggerHao 的方法解决了参考文献的问题，如果有和我一样用make的把makefile文件里的bibtex改成biber即可，msmake文件里也这么改就行，使用的版本为texlive2022

另外还有个小问题就是我有一篇参考文献标题里面有公式，会报错，然后编译出来显示是放在一行QAQ虽然公式没法转行他也没另起一行，而且这bst的语法实属有点哈人完全不敢改

**Comment by HeartForXI** [comment]
我在2022/6/4，按照@BiggerHao的方法解决了参考文献的问题，S.1;s.n问题，全大写问题等等，主要使用TeXStudio，在选项-设置-构建里，设置默认文献工具为Biber，若使用其他IDE应该也要进行相应的修改。
gbnamefmt=lowercase是用来解决全大写问题。

主要方法如下：
在正文里注释掉以下两行：
% \bibliographystyle{buaathesis} % 参考文献格式
%\bibliographystyle{GBT7714-2015}

在buaa.cls文件里注释掉以下四行：
% \RequirePackage[sort&compress]{natbib}
% \bibpunct{[}{]}{,}{n}{}{}
% \setlength{\bibsep}{0pt}
%\newcommand{\upcite}[1]{\textsuperscript{\cite{#1}}}

在tex主文件里的\begin{document}之前添加：
\usepackage[backend=biber,style=numeric,sorting=none,gbpub=false,bibstyle=gb7714-2015,citestyle=gb7714-2015,gbnamefmt=lowercase]{biblatex}
\addbibresource[location=local]{ref.bib}

在reference.tex或主文件参考文献部分注释掉下面第一行，添加第二行内容：
% \bibliography{ref}
\printbibliography
使用TeXStudio，在选项-设置-构建里，设置默认文献工具为Biber，若使用其他IDE应该也要进行相应的修改。

**Comment by HeartForXI** [comment]
我看了下我论文里也有这个双斜杠问题，我当时没发现，没有解决，不好意思帮不上忙。
















在 2023-05-08 17:08:08，"Gan Ziheng" ***@***.***> 写道：

请问下红色箭头处的//要怎么去掉？

请问同学怎么解决？

**Comment by GanZiheng** [comment]
> 我看了下我论文里也有这个双斜杠问题，我当时没发现，没有解决，不好意思帮不上忙。 在 2023-05-08 17:08:08，"Gan Ziheng" ***@***.***> 写道： 请问下红色箭头处的//要怎么去掉？ 请问同学怎么解决？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

没关系，谢谢。

**Comment by jingzhengli** [comment]
> bibliography

问题解决了。但是目录里面没有“参考文献了”
