### ISSUE TITLE
Win8.1下 安装WinEdt+Ctex 编译报错

### ISSUE THREAD

**Issue by txsing** [BHOSC/BUAAthesis#166]
Command Line:   texify.exe --pdf --tex-option=--interaction=errorstopmode --tex-option=--synctex=1 "C:\Users\tianxing\Downloads\BUAAthesis-master\BUAAthesis-master\sample-master.tex"
Startup Folder: C:\Users\tianxing\Downloads\BUAAthesis-master\BUAAthesis-master

This is pdfTeX, Version 3.1415926-2.3-1.40.12 (MiKTeX 2.9)
entering extended mode

(C:/Users/tianxing/Downloads/BUAAthesis-master/BUAAthesis-master/sample-master.
tex
LaTeX2e <2011/06/27>
Babel <v3.8m> and hyphenation patterns for loaded.

(C:\Users\tianxing\Downloads\BUAAthesis-master\BUAAthesis-master\buaathesis.cls
Document Class: buaathesis 2012/07/06 v0.8 The LaTeX template for thesis of BUA
A
Document Class `buaathesis' v0.8 by BHOSC (2012/07)
(C:\CTEX\MiKTeX\tex\latex\ctex\ctexbook.cls
Document Class: ctexbook 2011/03/11 v1.02c ctexbook document class
(C:\CTEX\MiKTeX\tex\latex\ctex\opt\ctex-common-opts.def)
(C:\CTEX\MiKTeX\tex\latex\ctex\opt\ctex-caption-opts.def)
(C:\CTEX\MiKTeX\tex\latex\ctex\opt\ctex-class-opts.def)
(C:\CTEX\CTeX\tex\latex\ctex\cfg\ctexopts.cfg)
(C:\CTEX\MiKTeX\tex\latex\ctex\def\ctex-loadclass.def
(C:\CTEX\MiKTeX\tex\latex\base\book.cls
Document Class: book 2007/10/19 v1.4h Standard LaTeX document class
(C:\CTEX\MiKTeX\tex\latex\base\bk12.clo)))
(C:\CTEX\MiKTeX\tex\latex\ctex\def\ctex-common.def
(C:\CTEX\MiKTeX\tex\latex\l3kernel\expl3.sty
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3names.sty
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3bootstrap.sty))
(C:\CTEX\MiKTeX\tex\latex\misc\etex.sty)
(C:\CTEX\MiKTeX\tex\latex\graphics\color.sty
(C:\CTEX\MiKTeX\tex\latex\00miktex\color.cfg)
(C:\CTEX\MiKTeX\tex\latex\pdftex-def\pdftex.def
(C:\CTEX\MiKTeX\tex\generic\oberdiek\infwarerr.sty)
(C:\CTEX\MiKTeX\tex\generic\oberdiek\ltxcmds.sty)))
(C:\CTEX\MiKTeX\tex\latex\graphics\graphics.sty
(C:\CTEX\MiKTeX\tex\latex\graphics\trig.sty)
(C:\CTEX\MiKTeX\tex\latex\00miktex\graphics.cfg))
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3basics.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3expan.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3tl.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3seq.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3int.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3quark.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3prg.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3clist.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3token.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3prop.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3msg.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3file.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3skip.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3keys.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3fp.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3box.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3coffins.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3color.sty)
(C:\CTEX\MiKTeX\tex\latex\l3kernel\l3luatex.sty))
(C:\CTEX\MiKTeX\tex\latex\etoolbox\etoolbox.sty)
(C:\CTEX\MiKTeX\tex\generic\oberdiek\ifpdf.sty)
(C:\CTEX\MiKTeX\tex\generic\ifxetex\ifxetex.sty)
(C:\CTEX\MiKTeX\tex\latex\graphics\keyval.sty)
(C:\CTEX\MiKTeX\tex\latex\tools\indentfirst.sty)
(C:\CTEX\MiKTeX\tex\latex\base\fix-cm.sty
(C:\CTEX\MiKTeX\tex\latex\base\ts1enc.def))
(C:\CTEX\MiKTeX\tex\latex\fancyhdr\fancyhdr.sty)
(C:\CTEX\MiKTeX\tex\latex\ctex\engine\ctex-cjk-engine.def
(C:\CTEX\MiKTeX\tex\latex\cjk\CJK.sty
(C:\CTEX\MiKTeX\tex\latex\cjk\mule\MULEenc.sty)
(C:\CTEX\MiKTeX\tex\latex\cjk\CJK.enc))
(C:\CTEX\CTeX\tex\latex\CJKpunct\CJKpunct.sty
(C:\CTEX\CTeX\tex\latex\CJKpunct\CJKpunct.spa))
(C:\CTEX\MiKTeX\tex\latex\ctex\engine\ctex-cjk-common.def)
(C:\CTEX\MiKTeX\tex\latex\ctex\fontset\ctex-cjk-winfonts.def
(C:\CTEX\MiKTeX\tex\generic\zhmetrics\zhwinfonts.tex
(C:\CTEX\MiKTeX\tex\generic\oberdiek\ifpdf.sty){C:/CTEX/UserData/pdftex/config/
pdftex.map{Unicode.sfd}{UGBK.sfd}}))))
(C:\CTEX\MiKTeX\tex\latex\ctex\def\ctex-caption.def)
(C:\CTEX\MiKTeX\tex\latex\ctex\def\ctex-class.def)
(C:\CTEX\MiKTeX\tex\latex\ctex\def\ctex-book.def))
(C:\CTEX\MiKTeX\tex\latex\ctex\def\ctex-gbk.def)
(C:\CTEX\MiKTeX\tex\latex\ctex\cfg\ctexcap.cfg
(C:\CTEX\MiKTeX\tex\latex\ctex\cfg\ctexcap-gbk.cfg))
(C:\CTEX\MiKTeX\tex\latex\ctex\cfg\ctex.cfg)
(C:\CTEX\MiKTeX\tex\latex\base\ifthen.sty)
(C:\CTEX\MiKTeX\tex\latex\ams\math\amsmath.sty
For additional information on amsmath, use the `?' option.
(C:\CTEX\MiKTeX\tex\latex\ams\math\amstext.sty
(C:\CTEX\MiKTeX\tex\latex\ams\math\amsgen.sty))
(C:\CTEX\MiKTeX\tex\latex\ams\math\amsbsy.sty)
(C:\CTEX\MiKTeX\tex\latex\ams\math\amsopn.sty))
(C:\CTEX\MiKTeX\tex\latex\amsfonts\amssymb.sty
(C:\CTEX\MiKTeX\tex\latex\amsfonts\amsfonts.sty))
(C:\CTEX\MiKTeX\tex\latex\jknappen\mathrsfs.sty)
(C:\CTEX\MiKTeX\tex\latex\tools\bm.sty)texify: pdflatex.exe failed for some reason (see log file).

_____________________________________________________________________

 PDFTeXify Compilation Report (Pages: 0)

 Errors: 0   Warnings: 0   Bad Boxes: 0
_____________________________________________________________________

**Comment by txsing** [comment]
(C:\CTEX\MiKTeX\tex\latex\tools\bm.sty)texify: pdflatex.exe failed for some reason (see log file).
pdflatex.exe出错误，不知道为什么....

**Comment by huxuan** [comment]
Please specify the compiling command you use.

P.S. BUAAthesis should be compiled via XeLaTeX as documented.

**Comment by JosephPeng** [comment]
请用Xelatex编译

**Comment by huxuan** [comment]
Close temporarily as no further response received, feel free to reopen it if you have any further question. @txsing
