### ISSUE TITLE
关于引用与链接的颜色问题

### ISSUE THREAD

**Issue by LiVincent-Zhang** [BHOSC/BUAAthesis#167]
我在用这个模板的过程中，发现引用和链接都是有颜色的，虽然最后黑白打印出来没有关系。但是电子版的文章可以有这个颜色么？

P.S. 用latex写的文章能拿去查重么？

谢谢各位啦~

**Comment by Klusting** [comment]
把\documentclass选项里的color去掉就没有颜色了

**Comment by huxuan** [comment]
有颜色是为了电子版打印方便的，documentclass 里面有选项可以设置成黑白的。
查重的话不是很清楚，但是不属于模板本身的问题了，所以这个 issue 就先关掉了哈，有问题可以随时reopen。
