### ISSUE TITLE
mhchem包会导致排版错误

### ISSUE THREAD

**Issue by Klusting** [BHOSC/BUAAthesis#168]
使用mhchem包后正文每一页内容都会上移，第一行会跑到页眉上面。

**Comment by JosephPeng** [comment]
Nope. 如下图所示，在导言区加入mhchem包后直接使用即可，排版无问题。
使用环境：Win7，TexLive2013，XeLatex编译，在最新的BUAAthesis模板上编译正常。
请题主确认是否代码OK，编译环境OK。

![q](https://cloud.githubusercontent.com/assets/1856720/7900381/b3f46132-0785-11e5-8e83-ce7484520a1e.jpg)

**Comment by JosephPeng** [comment]
Hi, @Klusting 
As there is no more response, I takes it as a "Fixed" and close this issue. If there are more infomations or questions, feel free to tell us.
