### ISSUE TITLE
请把thanks改名为acknowledgement

### ISSUE THREAD

**Issue by BrushXue** [BHOSC/BUAAthesis#169]
班里好几个同学吐槽过这个问题了，建议修改/data/bachelor/thanks.tex文件名为acknowledgement
这种低级词汇错误最好还是不要让全世界看到。

**Comment by huxuan** [comment]
@BrushXue Hi, thanks for your bug reporting. I would appreciate more if you send a pull request to solve this issue. :-)

**Comment by huxuan** [comment]
Fixed by commit 8d56eedeaa754cb7b4a717d23ad2fb80689a2f8a.
