### ISSUE TITLE
Subfigure不换页

### ISSUE THREAD

**Issue by LiVincent-Zhang** [BHOSC/BUAAthesis#170]
使用subfigure引入很多图片后，图片不会自动切分到第二个页面上。

![beddaad7-d891-4dfc-838e-9212dffbdb80](https://cloud.githubusercontent.com/assets/11719866/11084849/059ac6ea-887b-11e5-8d9c-80fc92b74679.png)

**Comment by huxuan** [comment]
这是subfigure本身的问题吧，似乎不是模板本身可以解决的……

**Comment by huxuan** [comment]
@JosephPeng 有啥意见不？

**Comment by LiVincent-Zhang** [comment]
@huxuan 我本来想试试subfloat的，但是在导言区加入\usepackage{subfig}报错。

`Undefined control sequence.`

因为对latex的模板语法不是很熟悉，所以想请问下，是否是加入的位置不对。


P.S. 系统OSX 10.11

**Comment by huxuan** [comment]
@LiVincent-Zhang 在自己的tex里加应该是不会有问题的

**Comment by JosephPeng** [comment]
Hi, @LiVincent-Zhang @huxuan 
目测是Sugfig这个包的问题, 我也无法提供更多的支持. 因为subfigure是在figure环境中的, 所以子图太多的话, 整个figure就会很长或很大, 超出页面大小, LaTeX无法对一个figure进行分割, 所以导致@LVincent-Zhang 所提的问题.
另外, 如果需要很的图需要用到subfigure的话, 建议将若干(比如4~6个左右)个子图放在一个figure里, 以供LaTeX正确浮动figure环境, 或者调整各个子图的大小, 使所有子图能够在一个page中放下(这样的话, 电子版的论文可以通过放大页面来查看图片细节, 但打印版估计就看不到太多的子图的细节了).

**Comment by JosephPeng** [comment]
Hi, @LiVincent-Zhang 
若没有问题的话, 我先关闭这个issue, 若有问题请再提交issue或comment, 多谢~

**Comment by LiVincent-Zhang** [comment]
谢谢。我整体缩小了图片，一页就能放下。
