### ISSUE TITLE
table中加脚注方法

### ISSUE THREAD

**Issue by jmaximelv** [BHOSC/BUAAthesis#171]
http://tex.stackexchange.com/questions/35615/footnote-in-table

\documentclass{article}
\usepackage{tablefootnote}
\begin{document}

\begin{table}
  %\begin{center}% replaced by \centering
  \centering
    %\begin{footnotesize}
     \begin{tabular}{|l|l|l|}
     \hline 
     TPA & Components & Cost \\ \hline
      & Total & 56558.4 \\ \hline 
     \end{tabular}
    %\end{footnotesize}
    \caption[Hardware cost estimation]{%
      Hardware cost estimation\tablefootnote{per router}\label{tab:}}
  %\end{center}
\end{table}
\end{document}

**Comment by huxuan** [comment]
Hi @jmaximelv , 我想你这个应该是算作sharing？如果文档中没有提到的话，可以考虑加到我们的文档里面~能提交PR什么的就更好了~

**Comment by jmaximelv** [comment]
PR什么意思？
原文档“chapter4-basic.tex”中有如下内容：
“如果在表格中需要使用脚注(footnote)功能，则需要将浮动表格环境置于一个minipage中，
否则脚注会被内容所吞掉。比如下表所示。但目前能力有限，无法将此表格居中，也无法添加
表格标题和引用。待改进。”

我直接将\usepackage{tablefootnote}加到buaathesis,cls中，并用tablefootnote代替footnote即可。

**Comment by huxuan** [comment]
@jmaximelv PR是pull request，是说把相应的内容加入到模板和文档里，然后以代码修改的形式提交上来。

**Comment by huxuan** [comment]
Close as we will discuss about it in #172
