### ISSUE TITLE
列表与中文习惯不一致

### ISSUE THREAD

**Issue by ericuni** [BHOSC/BUAAthesis#173]
列表的中文习惯一般是下面这样的, item 开始会缩进, 内容换行之后是与正文左对齐, 如图[1]所示.
我自己尝试了setlist的很多变量, leftmargin, labelindent, labelwidth, labelsep 但是没有成功.
[1]: http://imgbox.com/4YJKY9Gl

**Comment by huxuan** [comment]
http://tex.stackexchange.com/questions/78167/indentation-within-an-itemized-list

你指的是不是这个链接里的问题？这个应该算是LaTeX自带命令的使用吧，并不是模板里实现的内容，我把这个标记成为问题了（不是一个bug）

**Comment by ericuni** [comment]
是同一类的问题, 后面给出的解答还是没有达到我给出的图片的效果.
item 的label 应该缩进两个中文字符.
item 里面内容过长时, 换行后的开头应该与正文对齐, 而不是与item 内容的第一行对齐.

使得输入下面的内容
```Latex
Long text, long text, long text, long text, long text, long  text, long text, long text, long text, long text, long text, long  text, long text.

Standard itemize:
\begin{enumerate}
\item Test
\item Test
\item Long text, long text, long text, long text, long text, long  text, long text, long text, long text, long text, long text, long  text, long text.
\end{enumerate}
```
得到的结果为图[2].
也就是与输入下面的内容得到的结果一样
```Latex
Long text, long text, long text, long text, long text, long  text, long text, long text, long text, long text, long text, long  text, long text.

Standard itemize:

1. Test

2. Test

3. Long text, long text, long text, long text, long text, long  text, long text, long text, long text, long text, long text, long  text, long text.
```
[2]: http://imgbox.com/Z1PgLjnJ

**Comment by huxuan** [comment]
This may be useful. http://tex.stackexchange.com/questions/79938/hanging-indent-inside-list

Actually, I though you should Google it rather than asking help here, that will be more efficient.

As this is not a bug of BUAAthesis, I will close this issue.

**Comment by ericuni** [comment]
I just read your link, but it did not solve my problem.
And I have truly tried Google last night for a long time, but unfortunately still not found the answer.
The most close one is http://tex.stackexchange.com/questions/184780/can-someone-please-explain-the-enumitem-horizontal-spacing-parameters.
Finally, I have to use the hard code to achieve the desired effect.
Thanks anyway.

**Comment by ericuni** [comment]
I tried again and I made it.
http://imgbox.com/ommGP1H8
```Latex
\setlist[enumerate]{
    topsep=0pt,
    itemsep=0pt,
    partopsep=0pt,
    parsep=\parskip,
	labelindent=\parindent,
	labelwidth=1.3em,
	labelsep = .3em,
	itemindent=3.6em,
	leftmargin=!,
}
\setlist[itemize]{
    topsep=0pt,
    itemsep=0pt,
    partopsep=0pt,
    parsep=\parskip,
	labelindent=1.4em,
	labelwidth=1.3em,
	labelsep = .3em,
	itemindent=3em,
	leftmargin=!,
}

```

**Comment by huxuan** [comment]
赞~似乎这个问题 #174 里也提到了，我不太确定这些代码是不是应该放到buaathesis.cls里作为全局的设置。 @JosephPeng 有啥意见不？

@ericuni 如果你有意愿将这些代码加入到cls里并以pull request的方式提交上来那就最好了~

**Comment by ericuni** [comment]
待@JosephPeng 回复后, 我非常乐意以 pull request 的方式提交上去.

**Comment by JosephPeng** [comment]
Hi, @ericuni @huxuan 
最近一直在忙着搬砖，未及时登录查看消息，十分抱歉～
对于@ericuni 在#issue-119295118 提到的图 imgbox.com/4YJKY9Gl , 个人觉得更像是paragraph, 而不是一个item, 作为enumerate或itemize, 换行后与正文左侧对齐的话, (个人感觉)与其作为"条目"是有些不符. 即若能够直接以paragraph来实现, 为何仍需要(强行)作为enumerate或itemize来实现呢?

**Comment by ericuni** [comment]
Hi, @JosephPeng 
虽然使用paragraph 可以实现同样的效果， 但是列表中的编号数字需要手动指定，也就是会成为硬编码。

**Comment by JosephPeng** [comment]
Hi, @ericuni 
嗯，这样的话是硬编码，但对于使用者来说应该是更容易理解，也更快速的撰写论文。

对于这个PR，我个人也不置可否，或者，能否考虑新建一个环境，使其能够达到这个PR的效果，但也不覆盖原先的代码呢？

**Comment by sighingnow** [comment]
This issue can be avoid by using `enumerate` environment with `[wide]` option. I have also mentioned how to create list like this here 1aa7806. The result is similar to paragraphs and users don't need to hard code the sequence numbers (exactly what @ericuni desired).

It looks like as follows:

![fix-list-indentation](https://cloud.githubusercontent.com/assets/7144772/19381457/398178b0-922e-11e6-9f85-e75a0653f8d8.png)
