### ISSUE TITLE
章标题后首段没有段首缩进

### ISSUE THREAD

**Issue by nilday** [BHOSC/BUAAthesis#174]
很奇怪，就章标题后的第一段没有段首缩进。还有就是\begin{enumerate}里面的内容也没有缩进。

对于章标题，我试过手动加\indent \par\indent \par\setlength{\parindent}{2em} ，三种方式都不管用。

上图：
![enumerate](https://cloud.githubusercontent.com/assets/3797285/11457830/2a877a1c-96ee-11e5-9e28-461ca79c8ffc.png)
![zhangbiaoti](https://cloud.githubusercontent.com/assets/3797285/11457831/2aa789f6-96ee-11e5-862d-d6b085cdd8f1.png)

**Comment by hengshanji** [comment]
每章开始那里加quad就行发自网易邮箱大师
            在2015年11月29日 23:10，Howard 写道:很奇怪，就章标题后的第一段没有段首缩进。还有就是\begin{enumerate}里面的内容也没有缩进。

对于章标题，我试过手动加\indent \par\indent \par\setlength{\parindent}{2em} ，三种方式都不管用。

上图：

**Comment by LiVincent-Zhang** [comment]
我加的都是qquad 

Sent from Outlook




On Sun, Nov 29, 2015 at 5:13 PM -0800, "hengshanji" <notifications@github.com> wrote:












        每章开始那里加quad就行发自网易邮箱大师

            在2015年11月29日 23:10，Howard 写道:很奇怪，就章标题后的第一段没有段首缩进。还有就是\begin{enumerate}里面的内容也没有缩进。



对于章标题，我试过手动加\indent \par\indent \par\setlength{\parindent}{2em} ，三种方式都不管用。



上图：

**Comment by nilday** [comment]
我已经解决了首段缩进的问题，在buaathesis.cls文件中加入
% 首段缩进
\usepackage{indentfirst}

就是不知道有没有副作用。

\begin{enumerate}缩进的问题还没搞。

**Comment by huxuan** [comment]
@nilday 在sample的代码里似乎并没有出现相同的问题，能再确认一下是哪里的错误么？

@hengshanji @LiVincent-Zhang 希望最好不要用邮件直接回复的功能，登录到github上来之后就可以看到邮件回复的效果是多么糟糕了……

**Comment by huxuan** [comment]
#173 里面提到了关于 enumerate 的问题，可以参考一下看是否解决，以及希望能帮忙确定一下，那些关于enumerate的代码是否应该放到cls里呢？比如是否普遍使用，是否支持多级列表，毕业好多年的娃表示一忙起别的是就没啥动力来倒腾了……

**Comment by nilday** [comment]
sample中两个问题均出现了。
一个是第四章章标题后的文字。
![sample-](https://cloud.githubusercontent.com/assets/3797285/11562586/cbcc6f2c-9a09-11e5-8cab-654c54d48e07.png)
第二个是第四章的内容4.7.2
![sample-](https://cloud.githubusercontent.com/assets/3797285/11562585/cb9ae61e-9a09-11e5-916c-cadbad748e7d.png)

关于第一个问题，我查了一下，应该用
\usepackage{indentfirst}
解决，不知道是否有副作用。
关于第二个问题，我参考一下173的解决方案看看能不能行。

还有一个问题，关于页边距，cls文件中写到：
\newgeometry{
    top=25mm, bottom=25mm, left=30mm, right=20mm,
    headsep=5mm, headheight=10mm, footskip=10mm,
}
\savegeometry{mastergeometry}

我理解没错的话，应该是左侧3厘米右侧2厘米。我手头的格式文件写的是左右各2.5厘米。不知道这是一个bug还是学校对论文格式做出了调整。

**Comment by LiVincent-Zhang** [comment]
这个页边距问题我查了一下，根据研究生手册中的格式要求，上下左右的页边距各为25mm。template里面的设置应该是错了。


原始邮件
发件人:Howardnotifications@github.com
收件人:BHOSC/BUAAthesisBUAAthesis@noreply.github.com
抄送:Livinglivincentzhang@gmail.com
发送时间:2015年12月3日(周四) 22:07
主题:Re: [BUAAthesis] 章标题后首段没有段首缩进 (#174)


sample中两个问题均出现了。
 一个是第四章章标题后的文字。
 
 第二个是第四章的内容4.7.2

关于第一个问题，我查了一下，应该用
 \usepackage{indentfirst}
 解决，不知道是否有副作用。
 关于第二个问题，我参考一下173的解决方案看看能不能行。
还有一个问题，关于页边距，cls文件中写到：
 \newgeometry{
 top=25mm, bottom=25mm, left=30mm, right=20mm,
 headsep=5mm, headheight=10mm, footskip=10mm,
 }
 \savegeometry{mastergeometry}
我理解没错的话，应该是左侧3厘米右侧2厘米。我手头的格式文件写的是左右各2.5厘米。不知道这是一个bug还是学校对论文格式做出了调整。

**Comment by LiVincent-Zhang** [comment]
@huxuan 好的，我知道了。已经把多余的信息删掉了。

**Comment by huxuan** [comment]
@nilday 下图是我本地编译出来的结果，建议你先更新一下软件和宏包，因为模板是基于ctex的，所以感觉这个中文 specific 的问题应该已经解决了。

![image](https://cloud.githubusercontent.com/assets/726061/11582922/f29ec926-9a8e-11e5-9725-d87e0511a61a.png)

关于列表的，怎么说，我还是觉得不算是bug，而是在使用itemize的时候需要设置一些参数而已，因为列表的层次会不一样，感觉如果在模板里直接hard code的话，还是会有不适用的情况，可以参见 #173 里的设置。

P.S. 所有对模板的修改都强烈建议不要直接修改cls，而是保证cls和这里维护的版本一样以免让问题复杂化。想添加`indentfirst`宏包或者`setlist`的修改都可以放在`sample-bachelor.tex`或者`sample-master.tex`的`\begin{document}`之前就可以了。这个跟一般程序语言里的作用域一样，local的设置会自动添加/覆盖掉模板里的设置的。

@LiVincent-Zhang 首先感谢理解和支持哈，也是为了大家更好的沟通和交流。

关于页边距的问题，学校规定确实是25mm，但是考虑到装订其实本模板里的更合理一些。所以模板有些地方不是严格按照学校规定来的，而是更多的考虑了LaTeX本身应该保留的特质。至少我还没听说有谁因为这么细小的差异被吐槽说格式有问题的，装订出来应该是这样的设置看起来更舒服才对。就算到时候真的较上真了，自己本地改一下重新编译一下应该就好。我不是很支持在模板里完全严格的模仿，你要是有不同意见也尽管说哈~

**Comment by hengshanji** [comment]
章标题上面的空白距离太大，在哪改啊？

**Comment by JosephPeng** [comment]
Hi, @LiVincent-Zhang 
多谢积极提交issue, 关于本问题#174 , 请更新宏包后再确认一下是否"章标题后首段没有段首缩进"? 若是由宏包或环境引起的issue, 而不是BUAAthesis模板引起的, 此issue将作为invalid而close. 多谢~

**Comment by JosephPeng** [comment]
Since there is no more response from the reporter, this issue might seems be solved.
