### ISSUE TITLE
章节上下的间距如何调整

### ISSUE THREAD

**Issue by hengshanji** [BHOSC/BUAAthesis#176]
是修改 beforeskip 和 afterskip 吗？我试了一下觉得应该是，但是beforeskip= -0.5\baselineskip  间距还是太大，能不能太小一点，我改成-0.8\baselineskip 好像不起作用，-1\baselineskip也是没有效果。

**Comment by huxuan** [comment]
LaTeX的章节间距是有一套自己的计算公式算出来的，所以强烈不建议用word的思维来思考LaTeX的排版。如果一定要修改间距的话，我知道的方式有两种，一种方式是参见这个链接里的说明 [1]，另一种方式是在希望修改的地方用\vspace{-1em}之类的命令，如果有其他的好办法欢迎补充。

[1] http://tex.stackexchange.com/questions/101116/how-to-reduce-the-space-before-after-section-and-subsection

P.S. 不同的问题最好新开issue，在 #174 下面那无关的评论我已经删了。

**Comment by huxuan** [comment]
Close as no update from reporter. Feel free to reopen it if there is any further problem.
