### ISSUE TITLE
请问您的模版里面为什么不能加下标，我google了一下有人问了这个问题

### ISSUE THREAD

**Issue by heatinsjtu** [BHOSC/BUAAthesis#178]
但是我按照他的说法却行不通

**Comment by LiVincent-Zhang** [comment]
@heatinsjtu 你指什么下标？

**Comment by heatinsjtu** [comment]
指的是公式里面的下标
这个链接里也提问了http://bbs.ctex.org/forum.php?mod=viewthread&tid=68132

**Comment by LiVincent-Zhang** [comment]
@heatinsjtu 能不能把你不显示下标的那段公式给贴上来。我用这个模板写的毕业论文，一切都没有问题

**Comment by heatinsjtu** [comment]
可能我用的是之前的版本，我新下载了这个用luatex和luaLatex可以编译通过，怎样生成pdf?

**Comment by LiVincent-Zhang** [comment]
@heatinsjtu make master

**Comment by heatinsjtu** [comment]
这是linux下的命令？我在win下可以用吗？

**Comment by heatinsjtu** [comment]
问题解决了，用msmake，谢谢！

**Comment by LiVincent-Zhang** [comment]
@heatinsjtu close吧

**Comment by heatinsjtu** [comment]
OK
