### ISSUE TITLE
提示缺少hypernat.sty文件，但网上说这个文件功能和natbib已经合并了

### ISSUE THREAD

**Issue by daibluewater** [BHOSC/BUAAthesis#179]
如题，因为功能合并，所以hypernat在CTAN中被去掉了，正常更新package就没有这个sty了。于是我在cls中把
\RequirePackage{hypernat}
注释掉了

似乎也没问题。还没开始大规模使用， 不知道是不是真的没问题

说合并了的地方：
http://bbs.ctex.org/forum.php?mod=viewthread&tid=56735

**Comment by JosephPeng** [comment]
目测可以注释之，但我个人未验证。
根据链接给出的内容理解，可以直接注释(或删除)这个 `\RequirePackage{hypernat}`，但不排除有些用户使用版本过低或未更新package，建议master分支暂时保留。个人使用时可注释之。

**Comment by daibluewater** [comment]
好的，谢谢

**Comment by JosephPeng** [comment]
@daibluewater 
Thanks for your feedback, please let us know should you have any further questions about this cls.
