### ISSUE TITLE
模板左右留白距离不一致

### ISSUE THREAD

**Issue by lewisKit** [BHOSC/BUAAthesis#180]
生成的论文pdf的留白部分貌似左边的比右边的略宽一些。

不知道毕设会不会有影响，以及如何在cls里面进行调整？

**Comment by lewisKit** [comment]
看到了可以调整留白的距离，想问一下的是这个左右留白不一致时毕设的要求么？

**Comment by JosephPeng** [comment]
@lewisKit 
按[北航研究生院](http://graduate.buaa.edu.cn/ch/xuewei/index.jhtml)的[学位论文撰写规定](http://graduate.buaa.edu.cn/ch/u/cms/www/201510/29142644o5oi.doc)，其要求为“学位论文的上边距：25mm；下边距：25mm；左边距：25mm；右边距：25mm；”，因为考虑到论文为双面打印(当然可以设置为单面打印)，所以本模板对于页面左右的边距进行了相应的适当调整，以便适应打印装订的论文更"美观"。
我个人觉得，若是双面打印，页面左右留白空间有差别才是比较合理的。若对此有不明白之处，建议问一下学院教务的相关老师。或者，提交电子版的论文为左右间距一致，打印时的论文左右间距适当调整。

**Comment by lewisKit** [comment]
谢谢～

**Comment by JosephPeng** [comment]
It seems this issue has been solved, please feel free to raise an issue if there are some other problems about this cls.

**Comment by lewisKit** [comment]
如果是为了双面打印，那么奇数页和偶数页的左右间距应该是不一样的。比如奇数页应该是左边距30mm, 右边距20mm，那么偶数页应该就是左边距20mm，右边距30mm。我看我北大研究生师兄论文模板貌似就是奇数页和偶数页是轮换来的。不知道我说的对不对？

**Comment by JosephPeng** [comment]
Hi, @lewisKit 
是这样的，而且如果你使用目前的repo里的模板编译过的话，也会看到双面打印时左右边距会跟随奇偶页而变化。

**Comment by lewisKit** [comment]
您好，我编译成功了，但奇偶页的边距是一样的。

系统是Mac，用的是MacTex，用的是sublime Text2的latex插件环境下的，存在warning，如下：


TraditionalBuilder: Engine: xelatex. Invoking latexmk... done.

No errors. Warnings:

./sample-bachelor.tex: Package hyperref Warning: Rerun to get /PageLabels entry.
./sample-bachelor.tex:16: LaTeX Font Warning: Font shape `U/rsfs/m/n' in size <10.53937> not available(Font)              size <10.95> substituted on input line 16.
./sample-bachelor.tex:16: LaTeX Font Warning: Font shape `U/rsfs/m/n' in size <15.05624> not available(Font)              size <14.4> substituted on input line 16.
./sample-bachelor.tex: Package Fancyhdr Warning: \headheight is too small (12.0pt): Make it at least 41.47307pt.
./data/abstract.tex:9: LaTeX Font Warning: Font shape `U/rsfs/m/n' in size <16.06> not available(Font)              size <17.28> substituted on input line 9.
./data/chapter1-intro.tex:29: LaTeX Font Warning: Font shape `EU1/txtt/m/n' undefined(Font)              using `EU1/lmr/m/n' instead on input line 29.
./data/chapter2-config.tex:108: LaTeX Warning: Reference `code-compile' on page 4 undefined on input line 108.
./data/chapter2-config.tex:128: LaTeX Warning: Reference `code-make' on page 5 undefined on input line 128.
./data/chapter3-download.tex:22: LaTeX Warning: Reference `code-git-clone' on page 6 undefined on input line 22.
./data/chapter3-download.tex:33: LaTeX Warning: Reference `code-git-pull' on page 6 undefined on input line 33.
./data/chapter4-basic.tex:76: LaTeX Warning: Reference `tab-space' on page 9 undefined on input line 76.
./data/chapter4-basic.tex:142: LaTeX Warning: Reference `fig-sample' on page 10 undefined on input line 142.
./data/chapter4-basic.tex: LaTeX Warning: `!h' float specifier changed to `!ht'.
./data/chapter4-basic.tex:165: LaTeX Warning: Reference `tab-sample' on page 10 undefined on input line 165.
./data/chapter4-basic.tex:193: LaTeX Warning: Reference `tab-col' on page 11 undefined on input line 193.
./data/chapter4-basic.tex:201: LaTeX Warning: Reference `tab-row' on page 11 undefined on input line 201.
./data/chapter4-basic.tex:234: LaTeX Warning: Reference `equ-sample' on page 12 undefined on input line 234.
./data/chapter4-basic.tex:248: LaTeX Warning: Reference `code-c-sample' on page 12 undefined on input line 248.
./data/chapter4-basic.tex:267: LaTeX Warning: Reference `fig-mini-l' on page 12 undefined on input line 267.
./data/chapter4-basic.tex:267: LaTeX Warning: Reference `fig-mini-r' on page 12 undefined on input line 267.
./data/chapter4-basic.tex:283: LaTeX Warning: Reference `fig-sub' on page 13 undefined on input line 283.
./data/chapter4-basic.tex:284: LaTeX Warning: Reference `fig-sub-l' on page 13 undefined on input line 284.
./data/chapter4-basic.tex:284: LaTeX Warning: Reference `fig-sub-r' on page 13 undefined on input line 284.
./data/chapter4-basic.tex:300: LaTeX Warning: Reference `fig-matrix' on page 13 undefined on input line 300.
./data/chapter4-basic.tex:301: LaTeX Warning: Reference `fig-matrix-a' on page 13 undefined on input line 301.
./data/chapter4-basic.tex:301: LaTeX Warning: Reference `fig-matrix-b' on page 13 undefined on input line 301.
./data/chapter4-basic.tex:302: LaTeX Warning: Reference `fig-matrix-c' on page 13 undefined on input line 302.
./data/chapter4-basic.tex:302: LaTeX Warning: Reference `fig-matrix-d' on page 13 undefined on input line 302.
./data/chapter4-basic.tex: LaTeX Warning: `!h' float specifier changed to `!ht'.
./data/chapter4-basic.tex:333: LaTeX Warning: Reference `fig-tab-mix' on page 13 undefined on input line 333.
./data/chapter4-basic.tex:333: LaTeX Warning: Reference `tab-fig-mix' on page 13 undefined on input line 333.
./data/chapter4-basic.tex: LaTeX Warning: `!h' float specifier changed to `!ht'.
./data/chapter4-basic.tex:359: LaTeX Warning: Reference `tab-long-example' on page 13 undefined on input line 359.
./data/chapter4-basic.tex:410: Package longtable Warning: Column widths have changed(longtable)                in table 4.6 on input line 410.
./data/chapter4-basic.tex:415: LaTeX Warning: Reference `thm-assumption-example' on page 15 undefined on input line 415.
./data/chapter4-basic.tex:416: LaTeX Warning: Reference `thm-definition-example' on page 15 undefined on input line 416.
./data/chapter4-basic.tex:416: LaTeX Warning: Reference `thm-proposition-example' on page 15 undefined on input line 416.
./data/chapter4-basic.tex:417: LaTeX Warning: Reference `thm-remark-example' on page 15 undefined on input line 417.
./data/chapter4-basic.tex:417: LaTeX Warning: Reference `thm-axiom-example' on page 15 undefined on input line 417.
./data/chapter4-basic.tex:418: LaTeX Warning: Reference `thm-lemma-example' on page 15 undefined on input line 418.
./data/chapter4-basic.tex:418: LaTeX Warning: Reference `thm-theorem-example' on page 15 undefined on input line 418.
./data/chapter4-basic.tex:419: LaTeX Warning: Reference `thm-proof-example' on page 15 undefined on input line 419.
./data/chapter4-basic.tex:419: LaTeX Warning: Reference `thm-corollary-example' on page 15 undefined on input line 419.
./data/chapter4-basic.tex:420: LaTeX Warning: Reference `thm-example-example' on page 15 undefined on input line 420.
./data/chapter4-basic.tex:420: LaTeX Warning: Reference `thm-exercise-example' on page 15 undefined on input line 420.
./data/chapter4-basic.tex:421: LaTeX Warning: Reference `thm-conjecture-example' on page 15 undefined on input line 421.
./data/chapter4-basic.tex:421: LaTeX Warning: Reference `thm-problem-example' on page 15 undefined on input line 421.
./data/chapter4-basic.tex:425: LaTeX Font Warning: Font shape `EU1/FandolSong-Regular(1)/m/it' undefined(Font)              using `EU1/FandolSong-Regular(1)/m/n' instead on input line 425.
./data/chapter5-usage.tex:73: LaTeX Warning: Hyper reference `chapter-basic' on page 22 undefined on input line 73.
./data/chapter5-usage.tex:73: LaTeX Warning: Reference `chapter-basic' on page 22 undefined on input line 73.
./data/chapter5-usage.tex:78: Package natbib Warning: Citation `kottwitz2011latex' on page 22 undefined on input line 78.
./sample-bachelor.tex: Package natbib Warning: There were undefined citations.
./sample-bachelor.tex: Package longtable Warning: Table widths have changed. Rerun LaTeX.
./sample-bachelor.tex: LaTeX Font Warning: Size substitutions with differences(Font)              up to 1.22pt have occurred.
./sample-bachelor.tex: LaTeX Font Warning: Some font shapes were not available, defaults substituted.
./sample-bachelor.tex: LaTeX Warning: There were undefined references.
./sample-bachelor.tex: LaTeX Warning: Label(s) may have changed. Rerun to get cross-references right.


[Done!]


warning 有点多，不知道是哪儿影响了。

**Comment by JosephPeng** [comment]
Hi @lewisKit 
不清楚是否是你的设置的问题或是其他问题，建议你先将本repo重新下载后用xelatex编译一遍看一下。

**Comment by lewisKit** [comment]
就是刚下的repo重新用xelatex编译的。

**Comment by lewisKit** [comment]
@JosephPeng 
我还主要存在一些字体问题，我把这些warning解决了再试一下。谢谢
