### ISSUE TITLE
eps格式图片字体变粗

### ISSUE THREAD

**Issue by mainking2003** [BHOSC/BUAAthesis#181]
用Matlab得到fig格式的图片，并直接转存为eps格式。在使用模版中的多图并排排列时，左图正常，右图的字体和坐标数字总是自动加粗，变得很难看。尝试了将同一张图并排，依然左图正常，右图字体加粗。使用\includegraphics或overpic宏包加载图片，均有此问题。软件环境为CTeX 2.9.2.164+Windows XP。

\begin{figure}[h!] % [h!] 表示尽量排在当前位置
    \begin{minipage}{.5\textwidth} % .5\textwidth 表示正文宽度的一半
        \centering
        \begin{overpic}[width=220bp,tics=5]{figure/PMI_fault-free-height.eps}
        \put(45,0){\footnotesize{图片序号}}
        \put(0,30){\rotatebox{90}{\footnotesize{高度$h~(m)$}}}
        \end{overpic}
        \caption{情形1下两个PMI卡尔曼滤波器的高度估计误差}
        \label{ch4fig:height-fault-free}
    \end{minipage}
    \begin{minipage}{.5\textwidth}
        \centering
        \begin{overpic}[width=220bp,tics=5]{figure/PMI_fault-free-heading.eps}
        \put(45,0){\footnotesize{图片序号}}
        \put(0,30){\rotatebox{90}{\footnotesize{航向角$\psi~(^{\circ})$}}}
        \end{overpic}
        \caption{情形1下两个PMI卡尔曼滤波器的航向角估计误差}
        \label{ch4fig:heading-fault-free}
    \end{minipage}
\end{figure}

\begin{figure}[!htbp] % [h!] 表示尽量排在当前位置
    \begin{minipage}{.5\textwidth} % .5\textwidth 表示正文宽度的一半
        \centering
        \includegraphics[width=220bp]{figure/PMI_schematic.eps}
        \caption{情形1下两个PMI卡尔曼滤波器的横滚角估计误差}
        \label{ch4fig:pitch-fault-free}
    \end{minipage}
    \begin{minipage}{.5\textwidth}
        \centering
        \includegraphics[width=220bp]{figure/PMI_schematic.eps}
        \caption{情形1下两个PMI卡尔曼滤波器的横滚角估计误差}
        \label{ch4fig:roll-fault-free}
    \end{minipage}
\end{figure}

[thesis_gj_1 22.pdf](https://github.com/BHOSC/BUAAthesis/files/267763/thesis_gj_1.22.pdf)

**Comment by huxuan** [comment]
感觉应该是caption的字体被应用到了第二个图片中，可以试试在includegraphics前加一个`\normalfont` 试试？

**Comment by mainking2003** [comment]
试了一下，\normalfont好像对eps图片没有作用。

**Comment by huxuan** [comment]
稍微Google了一下感觉有可能是matlab到处时候的问题，建议关键字`Matlab eps text bold font`

**Comment by mainking2003** [comment]
@huxuan 谢谢你的建议。 我试着从matlab那端修改设置，依然没有作用。另外，我上传的pdf附件中，图9和10其实是同一张图，是从visio转pdf再转eps得到的，能看出同样存在自动加粗的现象。所以，我感觉是加载图片过程中出现了问题。
现在我把图片都转为jpg格式，回避了这个问题，图片在文中显示正常了，算是一种解决办法吧。

**Comment by huxuan** [comment]
嗯，用graphicx的话可以直接用png或者jpg的。那这个issue我就暂时关掉了。
