### ISSUE TITLE
I got the Error like that "Undefined control sequence. \setmainfont"

### ISSUE THREAD

**Issue by xiaozhaolook** [BHOSC/BUAAthesis#184]
when I tried to compile the tex file in both winEdt and TexStudio, I got the following Errors, How can I solve it ?
the Errors List
line 1: Missing \begin{document}. �
line 51: Undefined control sequence. \setmainfont
line 51: Missing \begin{document}. \setmainfont{T
line 55: Undefined control sequence. \setCJKmainfont
line 55: Undefined control sequence. \setCJKmainfont{�
line 55: Undefined control sequence. \setCJKmainfont{��
line 55: Undefined control sequence. \setCJKmainfont{宋
line 55: Undefined control sequence. \setCJKmainfont{宋�
line 55: Undefined control sequence. \setCJKmainfont{宋��
line 55: Undefined control sequence. \setCJKmainfont{宋体
line 76: Undefined control sequence. }
line 76: Undefined control sequence. }
line 154: Undefined control sequence. \ctexset
line 155: Missing \begin{document}. c
line 160: Missing number, treated as zero. beforeskip={-.5\baselineskip}
line 160: Illegal unit of measure (pt inserted). beforeskip={-.5\baselineskip}
line 161: Missing number, treated as zero. afterskip={\baselineskip}
line 161: Illegal unit of measure (pt inserted). afterskip={\baselineskip}
line 165: Missing number, treated as zero. beforeskip={.5\baselineskip}
line 165: Illegal unit of measure (pt inserted). beforeskip={.5\baselineskip}
line 166: Missing number, treated as zero. afterskip={.5\baselineskip}
line 166: Illegal unit of measure (pt inserted). afterskip={.5\baselineskip}
line 171: Missing number, treated as zero. beforeskip={.5\baselineskip}
line 171: Illegal unit of measure (pt inserted). beforeskip={.5\baselineskip}
line 172: Missing number, treated as zero. afterskip={.5\baselineskip}
line 172: Illegal unit of measure (pt inserted). afterskip={.5\baselineskip}
line 187: Undefined control sequence. \ctexset
line 188: Missing \begin{document}. c
line 189: Undefined control sequence. name={�
line 189: Undefined control sequence. name={��
line 189: Undefined control sequence. name={第
line 189: Undefined control sequence. name={第,�
line 189: Undefined control sequence. name={第,��
line 189: Undefined control sequence. name={第,章
line 190: Undefined control sequence. number={\chinese{chapter}
line 190: Undefined control sequence. number={\chinese{chapter}
line 3925: Package hyperref Error: Wrong driver option `xetex',(hyperref) because XeTeX is not detected. \ProcessKeyvalOptions{Hyp}
line 248: Undefined control sequence. }
line 248: Undefined control sequence. }
line 248: Undefined control sequence. }
line 248: Undefined control sequence. }
line 248: Undefined control sequence. }
line 248: Undefined control sequence. }
line 248: Undefined control sequence. }
line 248: Undefined control sequence. }
line 248: Undefined control sequence. }
line 248: Undefined control sequence. }
line 248: Undefined control sequence. }
line 248: Undefined control sequence. }
line 248: Undefined control sequence. }
line 248: Undefined control sequence. }
line 248: Undefined control sequence. }
line 248: Undefined control sequence. }
line 248: Undefined control sequence. }
line 248: Undefined control sequence. }
line 248: Undefined control sequence. }
line 248: Undefined control sequence. }
line 248: Undefined control sequence. }
line 248: Undefined control sequence. }
line 248: Undefined control sequence. }
line 248: Undefined control sequence. }
line 375: Undefined control sequence. \newtheorem_{proof}{证明}
line 375: Undefined control sequence. \newtheorem_{proof}{证明}
line 375: Undefined control sequence. \newtheorem_{proof}{证明}
line 375: Undefined control sequence. \newtheorem_{proof}{证明}
line 375: Undefined control sequence. \newtheorem_{proof}{证明}
line 375: Undefined control sequence. \newtheorem_{proof}{证明}
line 375: Undefined control sequence. \newtheorem_{proof}{证明}
line 375: Undefined control sequence. \newtheorem_{proof}{证明}
line 375: Undefined control sequence. \newtheorem_{proof}{证明}
line 375: Undefined control sequence. \newtheorem_{proof}{证明}
line 375: Undefined control sequence. \newtheorem_{proof}{证明}
line 375: Undefined control sequence. \newtheorem_{proof}{证明}
line 379: Undefined control sequence. \newtheorem{assumption}{假设}
line 379: Undefined control sequence. \newtheorem{assumption}{假设}
line 379: Undefined control sequence. \newtheorem{assumption}{假设}
line 379: Undefined control sequence. \newtheorem{assumption}{假设}
line 379: Undefined control sequence. \newtheorem{assumption}{假设}
line 379: Undefined control sequence. \newtheorem{assumption}{假设}
line 379: Undefined control sequence. \newtheorem{assumption}{假设}
line 379: Undefined control sequence. \newtheorem{assumption}{假设}
line 379: Undefined control sequence. \newtheorem{assumption}{假设}
line 379: Undefined control sequence. \newtheorem{assumption}{假设}
line 379: Undefined control sequence. \newtheorem{assumption}{假设}
line 379: Undefined control sequence. \newtheorem{assumption}{假设}
line 380: Undefined control sequence. \newtheorem{definition}{定义}
line 380: Undefined control sequence. \newtheorem{definition}{定义}
line 380: Undefined control sequence. \newtheorem{definition}{定义}
line 380: Undefined control sequence. \newtheorem{definition}{定义}
line 380: Undefined control sequence. \newtheorem{definition}{定义}
line 380: Undefined control sequence. \newtheorem{definition}{定义}
line 380: Undefined control sequence. \newtheorem{definition}{定义}
line 380: Undefined control sequence. \newtheorem{definition}{定义}
line 380: Undefined control sequence. \newtheorem{definition}{定义}
line 380: Undefined control sequence. \newtheorem{definition}{定义}
line 380: Undefined control sequence. \newtheorem{definition}{定义}
line 380: Undefined control sequence. \newtheorem{definition}{定义}
line 381: Undefined control sequence. \newtheorem{proposition}{命题}
line 381: Undefined control sequence. \newtheorem{proposition}{命题}
line 381: Undefined control sequence. \newtheorem{proposition}{命题}
line 381: Undefined control sequence. \newtheorem{proposition}{命题}
line 381: Undefined control sequence. \newtheorem{proposition}{命题}
line 381: Undefined control sequence. \newtheorem{proposition}{命题}
line 381: Undefined control sequence. \newtheorem{proposition}{命题}
line 381: Undefined control sequence. \newtheorem{proposition}{命题}
line 381: Undefined control sequence. \newtheorem{proposition}{命题}
line 381: Undefined control sequence. \newtheorem{proposition}{命题}
line 381: Undefined control sequence. \newtheorem{proposition}{命题}
line 381: Undefined control sequence. \newtheorem{proposition}{命题}
line 382: Undefined control sequence. \newtheorem{lemma}{引理}
line 382: Undefined control sequence. \newtheorem{lemma}{引理}
line 382: Undefined control sequence. \newtheorem{lemma}{引理}
line 382: Undefined control sequence. \newtheorem{lemma}{引理}
line 382: Undefined control sequence. \newtheorem{lemma}{引理}
line 382: Undefined control sequence. \newtheorem{lemma}{引理}
line 382: Undefined control sequence. \newtheorem{lemma}{引理}
line 382: Undefined control sequence. \newtheorem{lemma}{引理}
line 382: Undefined control sequence. \newtheorem{lemma}{引理}
line 382: Undefined control sequence. \newtheorem{lemma}{引理}
line 382: Undefined control sequence. \newtheorem{lemma}{引理}
line 382: Undefined control sequence. \newtheorem{lemma}{引理}
line 383: Undefined control sequence. \newtheorem{theorem}{定理}
line 383: Undefined control sequence. \newtheorem{theorem}{定理}
line 383: Undefined control sequence. \newtheorem{theorem}{定理}
line 383: Undefined control sequence. \newtheorem{theorem}{定理}
line 383: Undefined control sequence. \newtheorem{theorem}{定理}
line 383: Undefined control sequence. \newtheorem{theorem}{定理}
line 383: Undefined control sequence. \newtheorem{theorem}{定理}
line 383: Undefined control sequence. \newtheorem{theorem}{定理}
line 383: Undefined control sequence. \newtheorem{theorem}{定理}
line 383: Undefined control sequence. \newtheorem{theorem}{定理}
line 383: Undefined control sequence. \newtheorem{theorem}{定理}
line 383: Undefined control sequence. \newtheorem{theorem}{定理}
line 384: Undefined control sequence. \newtheorem{axiom}{公理}
line 384: Undefined control sequence. \newtheorem{axiom}{公理}
line 384: Undefined control sequence. \newtheorem{axiom}{公理}
line 1: Overfull \hbox (20.0pt too wide) in paragraph

**Comment by huxuan** [comment]
Please ensure you are using the latest version, both for TeX system and the BUAAthesis template.

**Comment by xiaozhaolook** [comment]
Yes, I am using the latest version both CTEX and TexLive and have tried the latest template 

发自我的 iPad

**Comment by sighingnow** [comment]
@xiaozhaolook Maybe you have built this template using pdflatex so that you got such error messages. Our template is only tested with xelatex. You can set xelatex as default compiler in TexStudio.

**Comment by sighingnow** [comment]
Close as problem solved.
