### ISSUE TITLE
声明页不带页眉

### ISSUE THREAD

**Issue by SpongebBob** [BHOSC/BUAAthesis#189]
任务书限定了行加下划线，要写一整段话非常不方便，替换使用\uline的话，换页就会出现问题。使用\newpage \thispagestyle{empty}太简单粗暴了，只能干掉一页的页眉页脚。如果这一页内容太多自动换页的话，就会在新的一页死而复生

**Comment by huxuan** [comment]
> 任务书限定了行加下划线，要写一整段话非常不方便

那种写法确实比较ugly，但是也是为了满足任务书的格式需求折中的办法，应该也只是要人工分行？至少暂时我并不知道什么更elegant的方法。

> 使用\newpage \thispagestyle{empty}太简单粗暴了，只能干掉一页的页眉页脚。如果这一页内容太多自动换页的话，就会在新的一页死而复生。

这个说的还是任务书？我印象中任务书的格式（页数）是固定的，所以当时就这么写了？不过这个倒是可以改的，在开始的地方设置pagestyle为empty，在任务书的最后再把pagestyle设置成原来的就可以了，有兴趣的话可以尝试一下交PR。

**Comment by sighingnow** [comment]
> 声明页不带页眉

声明页的页眉已经去除，页码也从下一页开始计算。

> 任务书限定了行加下划线，要写一整段话非常不方便

这个我再想想办法试试看。

> 如果这一页内容太多自动换页的话，就会在新的一页死而复生。

我觉得任务书应当保持两页的篇幅，并且按照毕设论文手册的格式分页。本科毕设手册中，声明页的内容是已经给出了，不会出现分页的问题。

**Comment by SpongebBob** [comment]
@huxuan  thx，多谢点拨。问题已解决，还有个小问题就是不知如何指定\uline下划线对齐所有行，使用\ulinel就没办法换行。
@sighingnow 我说的不是很明白，不声明页只是页眉的问题。而任务书的部分问题有如下：
1.\ulinel无法自动换行，换\uline可解
2.内容书简单的用\thispagestyle指定了单页的样式，但是如果内容太多自动分页了，下一页会出现页码和页眉。

**Comment by sighingnow** [comment]
When use `\uline` to underscore long text, you can use `\hfill` to padding current line with spaces. Please see pull request #191 .

**Comment by sighingnow** [comment]
Since the pull request #191 is still under review and this problem is not fixed in the HEAD version, we should live this issue open for better issue tracking.

**Comment by sighingnow** [comment]
Fixed in #196.

cc @SpongebBob In afraid of you don't get notification. Please update to the latest version of our template.
