### ISSUE TITLE
WIN10 WinEdt+CTeX “Sorry, but xelatex.exe did not succeed.”

### ISSUE THREAD

**Issue by CsterKuroi** [BHOSC/BUAAthesis#192]
Command Line:   xelatex.exe --interaction=errorstopmode --synctex=-1 "sample-bachelor.tex"
Startup Folder: C:\Users\Kuroi\Desktop\charitychain-tex

This is XeTeX, Version 3.14159265-2.6-0.99992 (MiKTeX 2.9)

Sorry, but xelatex.exe did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  D:/CTEX/UserData/miktex/log/xelatex.log

You may want to visit the MiKTeX project page, if you need help.

_____________________________________________________________________

 XeLaTeX Compilation Report (Pages: 0)

 Errors: 0   Warnings: 0   Bad Boxes: 0
_____________________________________________________________________

**Comment by sighingnow** [comment]
Our template is only tested with CTeX 2.9.3, please make sure you are working with this version of CTeX. You can the distribution package here: http://mirrors.ustc.edu.cn/ctex/unstable/ .

**Comment by CsterKuroi** [comment]
http://mirrors.ustc.edu.cn/ctex/unstable/

**Comment by CsterKuroi** [comment]
I just downloaded it from here:http://mirrors.ustc.edu.cn/ctex/unstable/

**Comment by sighingnow** [comment]
It seems that your CTeX version is correct. You also could try to build the sample thesis using our `msmake.bat` script in command line. Make sure that the folder where contains the `xelatex.exe` is in your `PATH` environment variable.

**Comment by CsterKuroi** [comment]
C:\Users\Kuroi\Desktop\charitychain-tex>xelatex
This is XeTeX, Version 3.14159265-2.6-0.99992 (MiKTeX 2.9)
**

C:\Users\Kuroi\Desktop\charitychain-tex>msmake bachelor
正在编译文件
This is XeTeX, Version 3.14159265-2.6-0.99992 (MiKTeX 2.9)

Sorry, but xelatex did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  D:/CTEX/UserData/miktex/log/xelatex.log

You may want to visit the MiKTeX project page, if you need help.
唉呀，生成论文失败了呢

**Comment by CsterKuroi** [comment]
I'm going to do:
1. Uninstall and reinstall
2. another PC
3. ……

**Comment by sighingnow** [comment]
@CsterKuroi At line 257 of `buaathesis.cls`, remove this line 

~~~tex
\RequirePackage{hypernat}
~~~

This should be a fix for these issue. I'm trying to figure out what has happened in recent commits.

**Comment by huxuan** [comment]
Since we have removed `hypernat` package in #194. Update the `BUAAthesis` package to the latest should resolve this problem. Issue closed and feel free to reopen it if there is any further related problem.

**Comment by Ellen-Cheng** [comment]
I met the same problem, did you go over it, bro?

**Comment by sighingnow** [comment]
> I met the same problem, did you go over it, bro?

May I know your texlive version?
