### ISSUE TITLE
任务书中的参考文献的换行问题

### ISSUE THREAD

**Issue by SpongebBob** [BHOSC/BUAAthesis#195]
如果使用国标引用英文参考文献。目测只能手动换行？无法自动换行。使\uline加下划线的换行方式目测只对中文生效？

**Comment by sighingnow** [comment]
As far as I know, put long text in `\uline` environment directly, as the following example:

~~~latex
\uline{Long Text Long Text Long Text Long Text Long Text Long Text Long Text
          Long Text Long Text Long Text Long Text Long Text Long Text Long Text
          Long Text Long Text Long Text \hfill} \\
~~~

The automatic line-break works well.

**Comment by SpongebBob** [comment]
I just write as this:

`        \uline{\buaa@bachelor@assign@ref@one\hfill} \\
`
 
![image](https://cloud.githubusercontent.com/assets/11678997/21477845/c16638a2-cb80-11e6-9b29-72adb1b89410.png)

But it shows like that:
![image](https://cloud.githubu
sercontent.com/assets/11678997/21477820/8eda832a-cb80-11e6-80b6-d83064c6c184.png)

**Comment by sighingnow** [comment]
Yes, the order of macro expanding does matter. Here, `\buaa@bachelor@assign@ref@one\hfill` should be expanded before `\uline`.

I will submit a commit soon to fix this issue. Currently, you could use `\uline` as the example above.

**Comment by huxuan** [comment]
AFAIK, this is more like a feature than a bug. It's an unsolved problem in previous version and that why we did the trick where there are 8 parameters for `\assignRef`, actually it is for 8 line of contents and needs line break manually. It's great to hear there is some solution now, I will take a further look on this.

**Comment by huxuan** [comment]
Hi @SpongebBob, thanks for using BUAAthesis and even more appreciate for the issue reports to help us improving it. But as I have clarified in the previous comment and also considering the discussion in #191. Manually line break is ugly implementation in some way but we have no better solution to make it support both automatic line break and same layout compared with the official assignment page sample. It is a long-term temporal work around that we may might in the future if there is a better way. If you are interested, you may refer to the commit 0ac4a3f0c2fc55750c8b84abdb953904dbaf1557 to see how to solve the underline long text wrap problem, but it is not friendly enough to common users so I suppose we won't merge it into the master branch. Sorry for closing this issue without solving it, but If you have any further related questions, feel free to reopen it again.
