### ISSUE TITLE
windows平台texlive2016模板编译出错

### ISSUE THREAD

**Issue by pipili0131** [BHOSC/BUAAthesis#200]
下载模板后，在texlive2016下编译，编译器xelatex，结果是没有目录，文中无论是对参考文献还是对章节，公式，图的引用全部出错，显示为“？”，编译时是一个undefined警告，这种情况怎么解决？

**Comment by sighingnow** [comment]
方便提供下错误信息吗？

**Comment by huxuan** [comment]
Maybe you need to run the `XeLaTeX` command twice?

**Comment by sighingnow** [comment]
以及编译步骤？用的是Makefile还是msmake.bat？如果是手动调用xelatex命令，Latex需要三遍才能正确生成完整的索引。@pipili0131

**Comment by pipili0131** [comment]
@sighingnow    谢谢回复，原来一直用xeletex编译，或来发现，必须用msmake.bat才可以。就是在最后的参考文献还是不对，博士论文的参考文献的输出内容不对。我用清华的版本直接替换bib也不行。不过已经非常感谢你们了。

**Comment by sighingnow** [comment]
@pipili0131 这个模板仅仅包含本科和硕士的模板。用于博士论文的话，可能不少地方都需要自己调整。
