### ISSUE TITLE
页边距不对

### ISSUE THREAD

**Issue by 1820366459** [BHOSC/BUAAthesis#204]
通过msmake bachelor进行编译，编译后的文档页边距不太符合要求，上面太宽下面太窄。请问是怎么回事？

**Comment by sighingnow** [comment]
具体哪个页面（比如目录、或者正文）有问题？可否贴个截图？

**Comment by 1820366459** [comment]
![qq 20170531144800](https://cloud.githubusercontent.com/assets/11703885/26619258/3767881c-4610-11e7-9165-8e6b38a24f54.png)
除了任务书看起来正常外，其他地方页边距都这样。是编译器的问题吗？

**Comment by yangalan123** [comment]
有什么进展吗？关于这个问题？

**Comment by yangalan123** [comment]
解决了，定位到CLS文件里geometry的定义，在页边距的定义中加入includefoot即可，参考：https://latex.org/forum/viewtopic.php?t=11335

**Comment by sighingnow** [comment]
@yangalan123 Thanks for working on this issue. Could you please submit a pull request for a fix?

**Comment by yangalan123** [comment]
Yes! I have created a PR #233

**Comment by huxuan** [comment]
@yangalan123 really appreciate it.

**Comment by sighingnow** [comment]
Closed in #204 by @yangalan123.
