### ISSUE TITLE
c

### ISSUE THREAD

**Issue by hdhqsmile** [BHOSC/BUAAthesis#207]
参考文献无法正常显示，均以?出现

**Comment by sighingnow** [comment]
是使用Makefile或 msmake.bat 编译的吗？

直接编译下载的样例是否存在同样的问题？

**Comment by xieyi4650** [comment]
@hdhqsmile  要编译四次，具体指令看Makefile或者msmake.bat

**Comment by sighingnow** [comment]
Closing as lacking of further response.
