### ISSUE TITLE
mactex出现找不到字体的错误

### ISSUE THREAD

**Issue by xieyi4650** [BHOSC/BUAAthesis#208]
不知道是不是我操作不对，clone之后，运行make master，出现了下面的错误。我之前在Windows和Ubuntu下都编译正确，最近刚换了电脑，不知道是哪里的原因。
fontspec error: "font-not-found" The font "STXingkai" cannot be found. For immediate help type H <return>. \maketitle

**Comment by sighingnow** [comment]
This error message means that the font "STXingkai" is not installed in your system. You need to install the font manually and try `make master` again. The following two links may help for your problem:

1. https://www.fontyukle.net/en/STXingkai.ttf
2. [How do I install fonts on my Mac?](https://www.fontspring.com/support/installing/how-do-i-install-fonts-on-my-mac)

**Comment by xieyi4650** [comment]
@sighingnow 
1、非常感谢，error已经解决了，还有一些warning，类似下面的。我在网上找到了关于这个问题的一些解答
https://tex.stackexchange.com/questions/266837/font-kaiti-sc-regular-does-not-contain-script-cjk
似乎这个警告⚠️无关紧要。
*************************************************
* fontspec warning: "script-not-exist"
*
* Font 'STSong' does not contain script 'CJK'.
*************************************************
2、一些字体的默认设置出了一些问题，输出信息提示已经用其他设置替换了。不知道你那里有没有完全正确的编译好的PDF文件。方便学习一下LaTeX，（新手使用LaTeX排版）

**Comment by sighingnow** [comment]
> 还有一些warning

Seems that this warning only appears on Mac OS, but I don't have access to a Mac. If pdf file could be generated successfully you could ignore this warning message, IMO.

> 不知道你那里有没有完全正确的编译好的PDF文件。

Someone (not me) has uploaded sample pdf files to BaiduDisk:  http://pan.baidu.com/s/1c0Xtq8o. I hope this will help.

**Comment by sighingnow** [comment]
Since the problem has been solved, I'm going to close this issue. Feel free to reopen if you have any further question.
