### ISSUE TITLE
参考文献必须全部引用么？

### ISSUE THREAD

**Issue by xieyi4650** [BHOSC/BUAAthesis#209]
文件：
data/reference.tex: 

line 5:
\nocite{*}

不需要将文献库中所有的文献都列出，应该如何操作？
mac os，mactex 2017

试过将这一行改为下面几种形式，还是出错。
\nocite{}
%\nocite{}
但是将通配符*换成某个具体文献的话，就不会出错。

所以想问，\nocite是必须要存在的么？那是不是要为毕设单独建立一个.bib文件

以下是出现的错误：
) [9] (./data/reference.tex [10] (./my-master.bbl

Package natbib Warning: Empty `thebibliography' environment on input line 8.

) [11] [12]) (./data/master/back1-achievement.tex

! LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.6

**Comment by sighingnow** [comment]
直接把 `data/reference.tex` 中的 `nocite{*}` 那一行去掉就行。

错误信息应该与这个无关。

**Comment by xieyi4650** [comment]
@sighingnow 直接去掉\novite{*}之后就会报这个错，但是报错位置不在Reference，是紧跟在Reference后面的那个文件。你那里能复现错误么？不能复现的话就是我电脑环境的问题。

**Comment by xieyi4650** [comment]
@sighingnow 找到原因了。是这样，我想搭毕设论文框架，就把正文部分的tex里的内容都删掉了，所以一个\upcite{}都没有，这个时候如果去掉\nocite{*}编译会出错。如果文中有至少一个引用，就不会报错。抱歉，麻烦你了。

**Comment by sighingnow** [comment]
嗯嗯好的，问题解决了就好~
