### ISSUE TITLE
chapter与页眉之间的行距不一致

### ISSUE THREAD

**Issue by nrm1** [BHOSC/BUAAthesis#210]
您好,在使用BUAA-master模板的时候,我编译的结果是,在正文部分,第一个chapter与页眉之间的行距为0,之后的chapter与页眉之间都是有行距的.我的编译环境是ubuntu16.04,xelatex.请问这个问题怎么解决?

**Comment by sighingnow** [comment]
直接编译sample-master（命令：`make master`）也有同样的问题吗？

**Comment by nrm1** [comment]
那个问题我没有找到解决方法,现在我换了一种思路,使用BUAA-bachelor并在它的基础上进行一些修改最后达到了我想要的效果,谢谢.
