### ISSUE TITLE
同一页面出现两张连续的图片的时候，第二张图片中的文字会被加粗

### ISSUE THREAD

**Issue by BiAiD** [BHOSC/BUAAthesis#211]
发现一个bug，就是在同一页面出现两张连续的图片的时候，第二张图片中的文字会被加粗。图片是eps格式的，如果图片不连续出现（比如这两个图片中间有正文的时候）则不会出现这个情况。
或者把下面这行.cls文件里面的代码中的\bf删除，也可以解决，但是图表标题的加粗效果就没了。
`\DeclareCaptionFormat{figure}{\bf\songti\zihao{5}{#1\textrm{#2}#3}}`

**Comment by BiAiD** [comment]
我看了一眼之前的已关闭的issue#181，也发现了这个问题，把eps文件换成png或jpg是一种方案，但是并没有真正解决呢。

**Comment by sighingnow** [comment]
能够提供你使用的EPS图片？

**Comment by sighingnow** [comment]
以及出问题的LaTeX？

**Comment by BiAiD** [comment]
已上传，请查收
[https://github.com/BiAiD/FileShare.git](url)

**Comment by BiAiD** [comment]
[https://github.com/BiAiD/FileShare](url)

**Comment by BiAiD** [comment]
？？？

**Comment by sighingnow** [comment]
我在Windows 10上一直没办法复现，不知道是不是缺粗体字体。

![image](https://user-images.githubusercontent.com/7144772/34814344-3dc19ad4-f6e8-11e7-8113-e160e85dd7d8.png)

**Comment by sighingnow** [comment]
你的LaTeX的环境和版本是？@BiAiD

**Comment by BiAiD** [comment]
我也是在Windows 10，用的texlive2016

**Comment by BiAiD** [comment]
你这个图的标题没有加粗

**Comment by sighingnow** [comment]
嗯，是的，所以我应该缺字体

**Comment by sighingnow** [comment]
你编译的是master还是bachelor？

**Comment by BiAiD** [comment]
是master

**Comment by sighingnow** [comment]
我修复了字体的问题，但依然不能复现。

这个EPS图片是怎么来的啊？PS导出的还是Visio导出的啊？

![image](https://user-images.githubusercontent.com/7144772/34823187-7f51e99c-f704-11e7-8d64-8134097a0c36.png)

**Comment by BiAiD** [comment]
是Visio另存为pdf，然后用Adobe Acrobat导出成eps的
你这个图题加粗后字体变成黑体了？不应该是宋体么？

**Comment by sighingnow** [comment]
我也纳闷呢...

**Comment by BiAiD** [comment]
我这边是宋体加粗了，不过就是连图片里的文字一块给加粗了。。

**Comment by BiAiD** [comment]
请问如果要开通四级标题该如何修改.cls文件？我试了添加下面这些代码，然而没有效果。
`\CTEXsetup[
    format={\zihao{-4}\bfseries},
    aftername={\quad},
    beforeskip={.5\baselineskip},
    afterskip={.5\baselineskip},
]{subsubsection}`

**Comment by BiAiD** [comment]
四级标题的编号问题已经解决了~

**Comment by songjinghe** [comment]
@BiAiD @sighingnow please show your code which can produce the error, also the material (*.eps) files, then we may dig into the problem

**Comment by songjinghe** [comment]
@BiAiD I can not replay your error. Although I got the caption shown with font SongTi (Bold). I'm using Ubuntu Mate 14.04, texlive 2017.
![screenshot-1](https://user-images.githubusercontent.com/3754416/38398708-2529b9d4-3978-11e8-9337-2ddca39bdf66.png)

**Comment by sighingnow** [comment]
@songjinghe The example provided by @BiAiD is at https://github.com/BiAiD/FileShare

See comments https://github.com/BHOSC/BUAAthesis/issues/211#issuecomment-355260048

I also can't reproduce this bug. Thanks for your attention and effort on this ticket.

**Comment by liueddd** [comment]
> 四级标题的编号问题已经解决了~

请问大佬是如何解决四级标题的问题的？

**Comment by sighingnow** [comment]
@liueddd 关于四级标题(aka. `subsubsection`)，可否提供比较官方的格式说明或样例？

如需自行修改的话，在此处修改增加定义目录中四级标题格式：

https://github.com/BHOSC/BUAAthesis/blob/dd6a109d0ffc15289b001bcd751b877902a9a7ca/buaathesis.cls#L201-L216

以及在此处定义四级标题在正文中的格式：

https://github.com/BHOSC/BUAAthesis/blob/dd6a109d0ffc15289b001bcd751b877902a9a7ca/buaathesis.cls#L153-L174

即可。

**Comment by sighingnow** [comment]
This bug should be fixed by #240 as well, has been confirmed on Windows with Texlive 2017.

Hi @BiAiD it is too late for you to know it has been fixed, but we still want to say thanks to you for helping us diagnose the problem!

Since the pr is ready and there is another related issue (#239) I'm going to closed this ticket.
