### ISSUE TITLE
提交查重时会显示PDF乱码

### ISSUE THREAD

**Issue by xieyi4650** [BHOSC/BUAAthesis#212]
win7 64位上的texlive2017
生成的PDF看起来一切正常，但是不知道为什么在淘宝上查重的时候提示乱码。。。需要怎么修改或者设置么

**Comment by sighingnow** [comment]
提交查重前可以考虑把PDF转换成Word，readme里有提到相关的工具。

/cc @xieyi4650

**Comment by xieyi4650** [comment]
@sighingnow 谢谢，
