### ISSUE TITLE
控制博士论文封面上华文行楷命令无效

### ISSUE THREAD

**Issue by JuilyLian** [BHOSC/BUAAthesis#215]
在buaathesis中挖掘博士论文封面上 “博士学位论文”六个字的华文行楷命令无效。已确定mac上有装该字体。

**Comment by huangteng1220** [comment]
请问在Mac怎样运行？能否指点一下。

**Comment by JuilyLian** [comment]
我是用的texMaker。

然后用XeLatex去build。
On Mar 15, 2018, at 2:26 PM, huangteng1220 <notifications@github.com<mailto:notifications@github.com>> wrote:


请问在Mac怎样运行？能否指点一下。

**Comment by huangteng1220** [comment]
好的，谢谢！能够运行了，但是封面是硕士的论文，有博士模版么？

**Comment by JuilyLian** [comment]
原来是同道中人。互勉。

将main文件中的第一行，改为

\documentclass[doctor,openright,twoside,color]{buaathesis}即可。

On Mar 15, 2018, at 2:44 PM, huangteng1220 <notifications@github.com<mailto:notifications@github.com>> wrote:


好的，谢谢！能够运行了，但是封面是硕士的论文，有博士模版么？

**Comment by huangteng1220** [comment]
OK，非常感谢！！雪中送碳啊！～～～对了，我这的“博士学位论文”六个字的华文行楷好像显示挺正常的

**Comment by JuilyLian** [comment]
你做了什么？为什么可以正常显示华文行楷？我换了个windows运行还是不行呢。求助呀。

不过我想到一个方法，若实在不行，我就求你帮忙在你机器上帮我编辑生成打印版了。😄

On Mar 15, 2018, at 2:50 PM, huangteng1220 <notifications@github.com<mailto:notifications@github.com>> wrote:


OK，非常感谢！！雪中送碳啊！～～～对了，我这的“博士学位论文”六个字的华文行楷好像显示挺正常的

**Comment by huangteng1220** [comment]
没问题的。你可以检查一下你的Mac字体册，有没有安装相关的字体。

**Comment by huangteng1220** [comment]
这个字体册在Mac的应用程序里面

**Comment by JuilyLian** [comment]
检查过了，是有这个字体的。不过，我也觉得是这里的问题。回头再好好查查它吧。

你至少让我知道，大神的模板是没有问题的。多谢！

On Mar 15, 2018, at 2:56 PM, huangteng1220 <notifications@github.com<mailto:notifications@github.com>> wrote:


没问题的。你可以检查一下你的Mac字体册，有没有安装相关的字体。

**Comment by huangteng1220** [comment]
那个目录和插图目录的字体为啥都是红色呢？你那怎么修改为黑色？

**Comment by huangteng1220** [comment]
打印出来的时候，有没有感觉字体颜色不对劲？

**Comment by JuilyLian** [comment]
是吗？我还真没打印过目录页。不对劲吗？


On Mar 15, 2018, at 4:50 PM, huangteng1220 <notifications@github.com<mailto:notifications@github.com>> wrote:


打印出来的时候，有没有感觉字体颜色不对劲？

**Comment by huangteng1220** [comment]
和旁边黑色字体有点不一样，你可以试一试。稍微注意的导师，估计会看出来的

**Comment by JuilyLian** [comment]
多谢告知。呆会儿看看。

On Mar 15, 2018, at 4:53 PM, huangteng1220 <notifications@github.com<mailto:notifications@github.com>> wrote:


和旁边黑色字体有点不一样，你可以试一试。稍微注意的导师，估计会看出来的

**Comment by sighingnow** [comment]
考虑打印的话，在模板中把`documentclass`的`color`选项去掉就行，代码位置：https://github.com/BHOSC/BUAAthesis/blob/master/sample-master.tex#L2

参考 https://github.com/BHOSC/BUAAthesis/pull/205

/cc @JuilyLian @huangteng1220

**Comment by sighingnow** [comment]
目前模板仅仅包括本科毕设和研究生毕设，不包括博士论文模板。

/cc @JuilyLian

**Comment by sighingnow** [comment]
Mac相关的问题我在 #216 下回复了，应该照着`Makefile`中的内容，使用 `xelatex` 命令就可以。

**Comment by JuilyLian** [comment]
天呀，你是说当前的模板不适用于博士论文？可是我看到有doctor选项。
如果不支持，我就惨了

发件人: Tao He [mailto:notifications@github.com]
发送时间: 2018年4月4日 17:46
收件人: BHOSC/BUAAthesis <BUAAthesis@noreply.github.com>
抄送: JuilyLian <lxl_tuizi@hotmail.com>; Mention <mention@noreply.github.com>
主题: Re: [BHOSC/BUAAthesis] 控制博士论文封面上华文行楷命令无效 (#215)


目前模板仅仅包括本科毕设和研究生毕设，不包括博士论文模板。

/cc @JuilyLian<https://github.com/JuilyLian>

**Comment by JuilyLian** [comment]
刚刚查阅了一下学校的论文标准，硕士和博士学位论文共用一套标准，只是在某些地方略有差异。但是封面页的华文行楷是都要的。

发件人: Tao He [mailto:notifications@github.com]
发送时间: 2018年4月4日 17:46
收件人: BHOSC/BUAAthesis <BUAAthesis@noreply.github.com>
抄送: JuilyLian <lxl_tuizi@hotmail.com>; Mention <mention@noreply.github.com>
主题: Re: [BHOSC/BUAAthesis] 控制博士论文封面上华文行楷命令无效 (#215)


目前模板仅仅包括本科毕设和研究生毕设，不包括博士论文模板。

/cc @JuilyLian<https://github.com/JuilyLian>

**Comment by sighingnow** [comment]
噢噢这样啊，目前的模板中，对博士论文只区分了标题，其他地方未区分。细节上可能有差异，如果使用时遇到的话欢迎反馈 😄 

标题的华文行楷的字体的问题，我明天在Windows上试一下然后答复你。Mac上字体的安装可以和 @huangteng1220  交流下 😃 

/cc @huangteng1220

**Comment by sighingnow** [comment]
cls文件中，在 https://github.com/BHOSC/BUAAthesis/blob/master/buaathesis.cls#L572 处已经将这几个字的字体设置为 hwxingkai 即 STXingkai 了，这种方式肯定是可以生效的，我试了下我本地（windows）编译出来的硕士论文的标题字体是正确的，在你那里出问题可能是环境的原因了。

`\setCJKfamilyfont`和`\CJKfamily`相关的一些用法参考 https://www.jianshu.com/p/b1751078e28e

最初没有采用直接`setCJKmainfont`的方式，应该也是处于某些兼容性考虑的workaround。

**Comment by sighingnow** [comment]
Close as solved.
