### ISSUE TITLE
这个latex版本能在Mac上运行么？

### ISSUE THREAD

**Issue by huangteng1220** [BHOSC/BUAAthesis#216]
我安装了“TeXLive 2016（推荐）”，能够顺利在Mac编辑中文的latex，但是这个版本还是没法运行。提示错误是undefined control sequence。有哪位高手可以指点一下怎么在Mac上运行使用。谢谢

**Comment by sighingnow** [comment]
可以的。至少在Windows上TexLive 2016是可以的，这个应该与运行的系统环境无关。

我没有Mac的环境，具体的话，你安装的是TexLive的哪个版本？可否尝试使用：https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/Images/

**Comment by huangteng1220** [comment]
@sighingnow 谢谢，可以运行了。里面的博士模版只是修改封面而已么？还有封面写上副导师的时候，没有显示出来

**Comment by sighingnow** [comment]
这个issue先关了，博士模板相关讨论转到 #215 下面。
