### ISSUE TITLE
做个冯如杯模板如何？

### ISSUE THREAD

**Issue by cgsdfc** [BHOSC/BUAAthesis#217]
我是一名北航学子。恰逢到了冯如杯学院打回修改再提交的时候。往年这个时候学院都会花费大量的进行格式审查和修改，而且我系冯如杯参加人数相当可观——使用ＬａＴｅＸ模板无疑会**极大的**减轻同学们的负担。　冯如杯的科技论文有完整的格式规范文件，覆盖了大部分情况；创业比赛要写策划书，虽然没有官方格式规定但是可以基于科技比赛的模板，而且策划书里面需要大量的图表绘制，如果能定义一些基于``ｔｉｋｚ/pgf``的宏是极好的。至于创业竞赛，可以视为简化版的科技竞赛。目前在ｇｏｏｇｌｅ上搜索 _冯如杯 latex 模板_ 只有一位[我航同学](https://github.com/Somedaywilldo/Someday-XeLaTex-Template) 做出来了，应该是可以用的，但是作为一个模板还有更多可以做的事情。

**Comment by sighingnow** [comment]
欢迎 pr 😄 

如果模板内容合适的话，我觉得我们可以在 BHOSC 这个organization下建一个新的repo也可以。

**Comment by cgsdfc** [comment]
开新ｒｅｐｏ不错。而且近期主要在忙毕设的事情，空闲的时候会考虑。我是ＬａＴｅＸ的新手，请多多指教！

**Comment by cgsdfc** [comment]
我把评论改了改，显得更像一个ｉｓｓｕｅ。要是真的有人接这个ｉｓｓｕｅ当然可以修改评论。

**Comment by cgsdfc** [comment]
问一下，如果格式要求里面明确提到“华文中宋”“华文新魏”这些具体的字体，是否需要指定字体文件``STZhongsong,华文中宋:style=Regular``；还是说笼统使用``\songti`` ``\xinwei`` ?

**Comment by cgsdfc** [comment]
已解决

**Comment by huxuan** [comment]
I would suggest to close this issue since it is not related to BUAAthesis. We should not bring more extra complexity, and it should be a totally new repo. This is more like a project idea rather than an issue belongs to this repo.

**Comment by sighingnow** [comment]
Closed as off-topic. If anyone has further comment or idea about the LaTeX template for 冯如杯，feel to reach me via email or join the QQ group :)
