### ISSUE TITLE
建议Release一个版本（附上编译好的PDF样例）

### ISSUE THREAD

**Issue by songjinghe** [BHOSC/BUAAthesis#218]
RT，建议修复完最近这波bug就Release一个版本吧，而且 **一定要把编译好的【本硕博】三个PDF文件一起发布出来**  （release的时候支持上传附件）。我感觉可能很多人想提前下载看看PDF的效果，而目前必须把源码下载下来自己编译（这个对于新手十分的不友好）

而且关于release的问题，从2012年一直讨论到现在，6年了，也讨论过很多次了。#53 #101

**Comment by sighingnow** [comment]
感谢建议，我想等 #211 ，#204 处理了之后发吧。邻近毕业季，估计也会有一些新的问题提出来。

预览的话，我先弄一个pre-release吧，传一下编译好的本硕博的PDF，方便大家预览。

**Comment by JosephPeng** [comment]
Closed as this issue have been solved in #219
