### ISSUE TITLE
两行一模一样的代码

### ISSUE THREAD

**Issue by cgsdfc** [BHOSC/BUAAthesis#220]
https://github.com/BHOSC/BUAAthesis/blob/a3e5d445c6d9a2555a757715da76dcd0e0511bc2/buaathesis.cls#L102-L108
104-105是两行一模一样的代码，我想是不是把第二行改成:
```tex
\renewcommand{\footrulewidth}{0pt}
```

**Comment by songjinghe** [comment]
agree

**Comment by sighingnow** [comment]
Thanks! 👍   A pull request for it is welcome! 👏 😉 😉

**Comment by sighingnow** [comment]
Close as fixed via #221 .
