### ISSUE TITLE
请问，doctor的模版 运行哪个tex

### ISSUE THREAD

**Issue by KingAndQueen** [BHOSC/BUAAthesis#222]
感谢！找到我航的latex了，请问，doctor的模版 运行哪个tex，还是要自己修改master的？

**Comment by huxuan** [comment]
把master模板里面的master参数改成doctor就可以了

**Comment by KingAndQueen** [comment]
thanks！ 搞定， 大家可以设置这里的doctor \documentclass[doctor,openright,twoside,color]{buaathesis}
