### ISSUE TITLE
双导师 双职称？

### ISSUE THREAD

**Issue by LeungGeorge** [BHOSC/BUAAthesis#224]
rt，定义为双导师时，职称需要手动加副导师职称（@ buaathesis.cls:932:）：

`buaathesis.cls:932:                指导教师姓名 & \makebox[9em][s]{\buaa@teacher\quad\buaa@subteacher\hfill} & 职\qquad 称 & \buaa@teacherdegree \\`

to：

`buaathesis.cls:932:                指导教师姓名 & \makebox[9em][s]{\buaa@teacher\quad\buaa@subteacher\hfill} & 职\qquad 称 & \buaa@teacherdegree\quad\buaa@teacherdegree \\`

**Comment by sighingnow** [comment]
对于双导师的情况，可以这样：给模板加上`twoteacher`选项：

    \documentclass[bachelor,openany,oneside,color,twoteacher]{buaathesis}

然后在 `data/com_info.tex`中定义副导师的**姓名**：

https://github.com/BHOSC/BUAAthesis/blob/a3c5200af9831da15607590d365e3f41e42c86b9/data/com_info.tex#L25-L29

在`data/master/master_info.tex`中定义副导师的**职称**：

https://github.com/BHOSC/BUAAthesis/blob/a3c5200af9831da15607590d365e3f41e42c86b9/data/master/master_info.tex#L6-L10

即可。
