### ISSUE TITLE
四级标题在目录中显示格式不对，怎么修改

### ISSUE THREAD

**Issue by huangteng1220** [BHOSC/BUAAthesis#226]
各位大神，我在文档开始处添加：
\setcounter{secnumdepth}{3}
\setcounter{tocdepth}{3}
能正常的显示
四级标题标号，也能在目录中显示四级标题，但是，字体和后面的点号有问题，请问怎么修改？谢谢！！

![a](https://user-images.githubusercontent.com/6296851/46119892-d9f15480-c23f-11e8-9c99-322363d5610d.png)

**Comment by huangteng1220** [comment]
已经解决了，谢谢大牛

**Comment by huxuan** [comment]
@huangteng1220 could you provide the solution so that other guys can have as reference?
