### ISSUE TITLE
请问如何将此模板应用于overleaf

### ISSUE THREAD

**Issue by 490** [BHOSC/BUAAthesis#227]
想用overleaf在线编辑，发现清华，哈工大等都有overleaf模板，请问如何将这份北航版导入overleaf？谢谢

**Comment by songjinghe** [comment]
直接上传不就行了？

**Comment by wokegrdws** [comment]
直接上传到overleaf或者下载来编译\maketitle有字体的问题。用的MacBook。

**Comment by songjinghe** [comment]
@wokegrdws 用的是xelatex吗？mac缺少Windows的字体肯定有问题啊，overleaf也可能缺字体。。。
mac的话自己安装一下字体吧。。。没有用过mac
overleaf那个如果缺字体就上传一下，然后我记得ctex里有个命令可以设置字体文件的。

**Comment by wokegrdws** [comment]
@songjinghe 用的是Xelatex。字体的问题出在“华文行楷”，因为Mac自带的字体中只有“华文楷体”。把.cls文件里的
```javascript
\setCJKfamilyfont{hwxingkai}{STXingkai}
```
改成
```javascript
\setCJKfamilyfont{hwxingkai}{STKaiti}
```
应该就可以了。不过还是有几个字体shape的warning，没仔细看。

**Comment by BuaaAlban** [comment]
windows下载下来也是不能用呀 请问overleaf解决了嘛

**Comment by wokegrdws** [comment]
@BuaaAlban 不会吧，Windows应该可以用吧。MacBook只要下载华文行楷字体就能基本正常用。

**Comment by BuaaAlban** [comment]
我在texstudio用的xelatex编译 他提示我有几个字体没有


朱博康
北京航空航天大学
中法工程师学院
地址：北京市海淀区学院路37号
邮编：100191
电话：13051576002
邮箱：buaazbk@buaa.edu.cn


Zhu bokang
Beihang University
Ecole Centrele de Pekin
Adress:No.37 College Road, Haidian District, Beijing
Tel: 13051576002
E-mail: buaazbk@buaa.edu.cn
在2019年4月25日 15:22，wokegrdws<notifications@github.com> 写道：

@BuaaAlban 不会吧，Windows应该可以用吧。MacBook只要下载华文行楷字体就能基本正常用。

**Comment by huxuan** [comment]
字体问题可以看一下这个issue #208

**Comment by BuaaAlban** [comment]
搞定啦 非常感谢!


朱博康
北京航空航天大学
中法工程师学院
地址：北京市海淀区学院路37号
邮编：100191
电话：13051576002
邮箱：buaazbk@buaa.edu.cn


Zhu bokang
Beihang University
Ecole Centrele de Pekin
Adress:No.37 College Road, Haidian District, Beijing
Tel: 13051576002
E-mail: buaazbk@buaa.edu.cn
在2019年4月25日 15:34，Xuan Hu (Sean)<notifications@github.com> 写道：

字体问题可以看一下这个issue #208

**Comment by BuaaAlban** [comment]
您好，我发现了咱们模板好像有一个小bug，就是在章节中，在换到新的一页后，新页和上一页不对齐，后面的页不受影响。请问您知道是怎么回事嘛


朱博康
北京航空航天大学
中法工程师学院
地址：北京市海淀区学院路37号
邮编：100191
电话：13051576002
邮箱：buaazbk@buaa.edu.cn


Zhu bokang
Beihang University
Ecole Centrele de Pekin
Adress:No.37 College Road, Haidian District, Beijing
Tel: 13051576002
E-mail: buaazbk@buaa.edu.cn
在2019年4月25日 15:44，朱博康<buaazbk@163.com> 写道：
搞定啦 非常感谢!


朱博康
北京航空航天大学
中法工程师学院
地址：北京市海淀区学院路37号
邮编：100191
电话：13051576002
邮箱：buaazbk@buaa.edu.cn


Zhu bokang
Beihang University
Ecole Centrele de Pekin
Adress:No.37 College Road, Haidian District, Beijing
Tel: 13051576002
E-mail: buaazbk@buaa.edu.cn
在2019年4月25日 15:34，Xuan Hu (Sean)<notifications@github.com> 写道：

字体问题可以看一下这个issue #208

**Comment by BuaaAlban** [comment]
貌似是奇偶数页码的左右留白宽度不一致导致的


朱博康
北京航空航天大学
中法工程师学院
地址：北京市海淀区学院路37号
邮编：100191
电话：13051576002
邮箱：buaazbk@buaa.edu.cn


Zhu bokang
Beihang University
Ecole Centrele de Pekin
Adress:No.37 College Road, Haidian District, Beijing
Tel: 13051576002
E-mail: buaazbk@buaa.edu.cn
在2019年5月1日 23:22，朱博康<buaazbk@163.com> 写道：




您好，我发现了咱们模板好像有一个小bug，就是在章节中，在换到新的一页后，新页和上一页不对齐，后面的页不受影响。请问您知道是怎么回事嘛


朱博康
北京航空航天大学
中法工程师学院
地址：北京市海淀区学院路37号
邮编：100191
电话：13051576002
邮箱：buaazbk@buaa.edu.cn


Zhu bokang
Beihang University
Ecole Centrele de Pekin
Adress:No.37 College Road, Haidian District, Beijing
Tel: 13051576002
E-mail: buaazbk@buaa.edu.cn
在2019年4月25日 15:44，朱博康<buaazbk@163.com> 写道：
搞定啦 非常感谢!


朱博康
北京航空航天大学
中法工程师学院
地址：北京市海淀区学院路37号
邮编：100191
电话：13051576002
邮箱：buaazbk@buaa.edu.cn


Zhu bokang
Beihang University
Ecole Centrele de Pekin
Adress:No.37 College Road, Haidian District, Beijing
Tel: 13051576002
E-mail: buaazbk@buaa.edu.cn
在2019年4月25日 15:34，Xuan Hu (Sean)<notifications@github.com> 写道：

字体问题可以看一下这个issue #208

**Comment by JosephPeng** [comment]
@BuaaAlban  不知道你用的是模板中使用的参数是 “oneside” 还是 “twoside”，根据这个参数的不同，oneside的奇偶而边距是不会变的，twoside的奇偶页的边距会根据奇数页和偶数页变换的，以适应双面打印。

**Comment by sighingnow** [comment]
I have tried to sync this repo to overleaf for better user experiences. It works fairly well to build and generate PDF targets, but the most concern is about the license of fonts. Some fonts used by this template may need to obey certain licenses of Microsoft. But I'm not very sure about that since I'm not an expert on font licenses.

It seems that overleaf has also support something like "fork", it would be great if we can provide a base project (and give a link in our README.md) to our users. If someone has any ideas about this problem feel free to comment here. Any help would be truly appreciated!

**Comment by huxuan** [comment]
Close as overleaf is non-goal **currently**.
