### ISSUE TITLE
宋体加粗问题

### ISSUE THREAD

**Issue by dongb5** [BHOSC/BUAAthesis#228]
你好，我编译之后需要宋体加粗（如图题，表题等）没有加粗，请问如何解决？我是win10+texlive2018+texstudio，用xelatex编译。

**Comment by JosephPeng** [comment]
图、表的标题已经按官方的要求定义了格式了。如果需要自行修改的话，需要手动修改cls文件里的相应代码(大概是在cls文件的405行至431行)。

**Comment by sighingnow** [comment]
Duplicate with #239 and will be fixed by #240.
