### ISSUE TITLE
texlive2018好像编译不过

### ISSUE THREAD

**Issue by Inception41** [BHOSC/BUAAthesis#230]
大佬学长们，我现在用的texlive2018，编译不过，各种问题（以前系统重装之前用的texlive2016，没问题），请问我只能卸载2018重装texlive2016解决吗？谢谢各位了！

**Comment by kjgfcdb** [comment]
我也遇到了编译不过的问题，看MakeFile中将bibtex前加了横线表示忽略出错，如果删除这个横线，那么编译总是会在bibtex阶段出错，以下是出错的Log
```
Database file #1: data/bibs.bib
You can't pop an empty literal stack for entry DBLP:conf/nips/2017
while executing---line 5913 of file buaathesis.bst
(There were 42 error messages)
```
在网上搜索了以下，猜测可能是buaathesis.bst文件中定义了一些FIELD但是在我的bib文件中没有，我的bib文件内容如下：
```
@proceedings{DBLP:conf/nips/2017,
  editor    = {Isabelle Guyon and
               Ulrike von Luxburg and
               Samy Bengio and
               Hanna M. Wallach and
               Rob Fergus and
               S. V. N. Vishwanathan and
               Roman Garnett},
  title     = {Advances in Neural Information Processing Systems 30: Annual Conference
               on Neural Information Processing Systems 2017, 4-9 December 2017,
               Long Beach, CA, {USA}},
  year      = {2017},
  timestamp = {Mon, 27 Nov 2017 12:38:16 +0100},
  biburl    = {https://dblp.org/rec/bib/conf/nips/2017},
  bibsource = {dblp computer science bibliography, https://dblp.org}
}
```
目前的问题是：
1. 在编译过程中忽略bibtex出错会不会有什么问题？
2. 如果想要修复这个出错，有没有可行的办法？

谢谢！

**Comment by JosephPeng** [comment]
@kjgfcdb bibtex是用来生成"参考文献"的，如果去掉bibtex，则论文中引用的"参考文献"将会显示为"?"，附录的“参考文献”章节也会为空白。

**Comment by sighingnow** [comment]
TexLive 2018 should be OK (on my windows). The error in the following log seems to be ignorable.

```
You can't pop an empty literal stack for entry DBLP:conf/nips/2017
while executing---line 5913 of file buaathesis.bst
(There were 42 error messages)
```

@Inception41 @kjgfcdb Could you please provide a full version of your error log?

**Comment by kjgfcdb** [comment]
@sighingnow My error log is same as yours. I know the errors can be ignored now, just use the `msmake.bat` in windows or the `MakeFile` in *nix. Anyway, thanks for your reply.

**Comment by sighingnow** [comment]
Thanks for your feedback. I'm going to close this issue as solved.
