### ISSUE TITLE
diagbox包导致排版出错

### ISSUE THREAD

**Issue by wokegrdws** [BHOSC/BUAAthesis#231]
使用`diagbox`宏包制作斜线表头的时候，会导致章节标题的间距等出错。只要使用`\usepackage{diagbox}`就出错。

**Comment by sighingnow** [comment]
I don't know how to use the `diagbox` package. But I have tried that putting `\usepackage{diagbox}` in `sample-bachelor.tex` (after `documentclass` and before `\begin{document}`) the build process can generate the target PDF as usual, without any errors.

Could you please provide more information about your trouble? For example the version of texlive, where you write `\usepackage{diagbox}` and the error message during building as well?

**Comment by sighingnow** [comment]
Closed as lacking response from the author.
