### ISSUE TITLE
texlive2016编译出来的pdf知网查重时目录没能被忽略

### ISSUE THREAD

**Issue by YOULLNEVERWA** [BHOSC/BUAAthesis#232]
目录里有4000+"."，导致查重率GG，换成texlive2018后目录能够被知网查重成功忽略

**Comment by sighingnow** [comment]
I would fix that by recommending TexLive 2019 in readme :)

**Comment by sighingnow** [comment]
Closed as we assume that users are working with texlive newer than 2017.
