### ISSUE TITLE
xelatex编译顺序问题

### ISSUE THREAD

**Issue by yangalan123** [BHOSC/BUAAthesis#234]
我不确定是否和windows环境以及texlive 2019有关系...但是我在写作我的毕设论文时如果直接用bat文件，会导致编译出的PDF不少引用无法链接（显示问号），我查了stackoverflow，感觉bat这个编译顺序：bibtex->xelatex->xelatex不是很对？比较通用的应该是xelatex->bibtex->xelatex->xelatex，我自己写了个shell是这么编译的就没问题

**Comment by sighingnow** [comment]
The command sequence invoked by `msmake.bat` is also `xelatex->bibtex->xelatex->xelatex`, and is the same with what invoked in `Makefile`.
