### ISSUE TITLE
texlive2017 编译报错

### ISSUE THREAD

**Issue by AlienMarkWong** [BHOSC/BUAAthesis#235]
![image](https://user-images.githubusercontent.com/31840432/67756999-f9c3ff00-fa75-11e9-93b1-9890c880c32f.png)

**Comment by yangalan123** [comment]
请check一下您的latex的package的安装情况，可能有遗失的内容。从log上来看可能对中文的支持不完全。

**Comment by sighingnow** [comment]
用的是xelatex来编译吗？在TexStudio里面可能需要选择或者设置一下。

**Comment by sighingnow** [comment]
Closed as lacking of response.
