### ISSUE TITLE
硕士学位论文目录中条标题字体不符合推荐

### ISSUE THREAD

**Issue by BiggerHao** [BHOSC/BUAAthesis#238]
根据“北京航空航天大学研究生撰写学位论文的规定（2009 年 7月）”文后的“附件15 博（硕）士学位论文目录格式”，“条标题用五号宋体、 1.5倍行距”。但是目前的模板中，条标题用的似乎是黑体，建议进行修改。

**Comment by sighingnow** [comment]
同一文件的第三页3.1.3要求“条标题：小四号黑体居左”。

**Comment by BiggerHao** [comment]
> 同一文件的第三页3.1.3要求“条标题：小四号黑体居左”。

@sighingnow 第三页的那个要求说的应该是条标题在正文中的样式，而非在目录中的样式。比如第三页还要求章标题居中。

**Comment by sighingnow** [comment]
Confirmed, will be fixed by #241. Thanks for bringing this up.
