### ISSUE TITLE
硕士论文模板图标题的字体问题

### ISSUE THREAD

**Issue by q623436923** [BHOSC/BUAAthesis#239]
![捕获33](https://user-images.githubusercontent.com/57673709/68681706-d4b7ac00-059e-11ea-9962-01f43b91939c.PNG)
![捕获34](https://user-images.githubusercontent.com/57673709/68681921-3d9f2400-059f-11ea-94e1-2006df8abbfc.PNG)
下载的硕士论文模板源码，然后用XeLaTex进行编译，发现图片的标题字体并不是黑体，与模板里给的硕士论文模板样例sample-master.pdf中图片标题字体不一样，第一张图为我自己通过XeLaTex编译生成的pdf，第二张图为硕士论文模板样例的pdf。按照规定格式图片标题字体是黑体，但是自己编译后得到的却不是，请问该怎么解决这个问题

**Comment by sighingnow** [comment]
根据《北京航空航天大学 研究生撰写学位论文的规定 （2009 年 7 月修订）》，图、表标题应该为“五号宋体加粗”，请问可否提供“按照规定格式图片标题字体是黑体”的来源？

至于宋体没有正确加粗的问题，已经在 #240 中修正。
