### ISSUE TITLE
代码标题不居中

### ISSUE THREAD

**Issue by BiggerHao** [BHOSC/BUAAthesis#243]
![代码标题不居中](https://user-images.githubusercontent.com/7645930/69050637-732f8b80-0a3d-11ea-85e3-9e8cc592e1c8.png)
上面这张图应该可以很明显地看出来“代码2.5 编译步骤”是不居中的，我在使用algorithm环境的时候也有类似的问题（使用boxed模式，算法标题出现在下方，但是略微偏左，不居中），请问如何才能使标题居中呢？

**Comment by sighingnow** [comment]
这个应该listings这个package的问题，你可以把listing放在一个figure里面，或者minipage里面，不要使用lsting的标题。

晚点fix。

**Comment by sighingnow** [comment]
Has been fixed in master.

Bachelor:

![image](https://user-images.githubusercontent.com/7144772/144789940-70a52926-2e32-4ba7-9955-1bb51a95ba61.png)

Master:

![image](https://user-images.githubusercontent.com/7144772/144789950-4d632fba-f50a-45a2-912b-6840d579fda1.png)
