### ISSUE TITLE
online类型的参考文献的标识有误

### ISSUE THREAD

**Issue by BiggerHao** [BHOSC/BUAAthesis#244]
目前的版本里，online类型的参考文献的标识是[M]，但是我用其他GB7714格式生成的都是[EB/OL]。不知道这算不算一个错误呢？

测试样例：
bib文件如下：
```
@misc{chollet2015keras,
  title={Keras},
  author={Chollet, Fran\c{c}ois and others},
  year={2015},
  howpublished={\url{https://keras.io}},
}

@online{chollet2015keras2,
  title={Keras},
  author={Chollet, Fran\c{c}ois and others},
  year={2015},
  url={https://keras.io},
}
```
第一条misc记录生成的参考文献如下：
```
[1] Chollet F., et al. Keras[缺文献类型标志代码].
```
第二条online记录生成的参考文献如下：
```
[2] Chollet F., et al. Keras[M].[S.l.]: [s.n.] , 2015. https://keras.io.
```
我看到online类型似乎是BibLaTex才支持的，不过在这里用BibTex似乎也出现什么问题，只是类型标识成了[M]。反而是BibTex支持的misc类型，这里变成了“缺文献类型标志代码”。

**Comment by Archer-Tatsu** [comment]
misc里加一个entry
typeoflit={EB/OL}
可解

**Comment by huxuan** [comment]
@BiggerHao Hi, we have update the bst file, could you help to confirm whether the problem is resolved or not?

**Comment by BiggerHao** [comment]
@huxuan The new bst file works fine for me. I tried the same bib file with the latest repository and it gave me two same records in the reference section.
Below is the .bib file:
```
@misc{chollet2015keras,
  title={Keras},
  author={Chollet, Fran\c{c}ois and others},
  year={2015},
  howpublished={\url{https://keras.io}},
}

@online{chollet2015keras2,
  title={Keras},
  author={Chollet, Fran\c{c}ois and others},
  year={2015},
  url={https://keras.io},
}
```
Below are the results I got:
```
[1] CHOLLET F, et al. Keras[EB/OL]. 2015. https://keras.io.
[2] CHOLLET F, et al. Keras[EB/OL]. 2015. https://keras.io.
```

**Comment by huxuan** [comment]
@BiggerHao Great, thanks for the prompt feedback.

Close as the issue resolved.
