### ISSUE TITLE
黑体加粗没效果

### ISSUE THREAD

**Issue by liueddd** [BHOSC/BUAAthesis#245]
模板中的涉及中文黑体加粗的格式，比如，“摘要”、“目录”、“关键字”等字，没有加粗效果。
尝试在模板中使用\bf，不管怎么调\bf与\heiti命令和\zihao命令的顺序，编译结果都是黑体未加粗的。

环境：windows10，texlive2019，在documentclass里面加了fontset=windowsnew选项。

形式审查，"目录"处被标记了格式不对。在线等，急。

**Comment by sighingnow** [comment]
Confirmed with the author of this issue that the font error is caused by lacking of simhei-Bold font.

Close as solved.
