### ISSUE TITLE
关于bst

### ISSUE THREAD

**Issue by huxuan** [BHOSC/BUAAthesis#246]
很久没真正参与到项目的开发中了，特别感谢 @sighingnow （应该也毕业了吧）还坚持维护这个项目，解答问题。

发现最近好几个问题都是跟bst相关的，简单搜了一下，发现现在github上已经有类似项目[1][2]，主要用的是这两版bst[3][4]。我们是不是也可以考虑更新一下bst，最繁琐的应该是验证工作，是不是可以考虑搞个dev branch之类的，让有心人帮忙测试一下，或者搞成选项让大家可以选之类的~

[1] https://github.com/CheckBoxStudio/BUAAThesis
[2] https://github.com/KagamiChan/BUAAthesis-mod
[3] https://github.com/CTeX-org/gbt7714-bibtex-style
[4] https://github.com/Haixing-Hu/GBT7714-2005-BibTeX-Style

**Comment by liueddd** [comment]
关于bst，我提了pr。用的是[3]里面那个改的。这个看起来像个比较官方的实现。我做了一些改动，主要是为了去掉[S.l.][s.n.]这种挺不好看的东西。
我的pr中，保留了原来的\upcite命令，同时，可以与\cite命令兼容，即可以用\cite命令打出来正常大小的不带上标的引用，这样行文会更方便一点。
主要是标准的问题，看了新版2015版的国标，其中改动比较大的是作者姓氏的写法，要求，姓氏全大写，名保留大写首字母且不带‘.’。这个改动算是挺大的了。我用的这版bst，正好完美实现了这个。
本人即将硕士毕业，用的就是这个模板，挺好用的。传上来，希望给后人留点东西。

**Comment by sighingnow** [comment]
@liueddd  Thank you for the work and I have commented under #247.

**Comment by sighingnow** [comment]
And AFAK the official requirement says our thesis should follow gb/t-7714 2005, not gb/t-7714 2015 :)

**Comment by Htallone** [comment]
这个参考文献著录，每个学校可能不同，不同年级可能也不同，研究生手册给的例子本身可能都有问题。我现在就用@misc{label, note = {XXX. YYY, ZZZ}}这种，note里面就是按照研究生手册中要求写的，每个参考文献都这样写，录入效率和word差不多；但是后面引用、排序等就方便多了，这也是一种临时策略吧

**Comment by huxuan** [comment]
个人意见，我们可以考虑换成[3]或者[4]中的一种，当然有什么别的option也欢迎大家提出，然后最好可以在使用说明中说明不同的利弊，包括 @liueddd 提供的版本也可以列出来，目前的这个版本有些过于陈旧了，应该还是从ctex论坛里面拔下来的版本，肯定没有github上的well maintained。

**Comment by huxuan** [comment]
Closed by #250 & #251, thanks again for the contribution! @liueddd
