### ISSUE TITLE
TeXstudio编译报错

### ISSUE THREAD

**Issue by AirTaker** [BHOSC/BUAAthesis#253]
求助一下各位大佬，编译其他模板的时候可以正常编译，但是编译这个毕设模板的时候会报错，不知道问题出在哪里，谢谢各位了！
环境：win10   TeXstudio 2.12.16   ctex 2.9.2
![1](https://user-images.githubusercontent.com/49189171/74152433-3db7ca00-4c49-11ea-9ca5-f19d87fc08c1.PNG)

![2](https://user-images.githubusercontent.com/49189171/74152445-43151480-4c49-11ea-86bc-1aea18fdbd1f.PNG)

**Comment by huxuan** [comment]
看错误信息好像是没有安装 CTeX 包？

两个小建议：
1. 最好确保 cls 是最新版本的
2. 最好能提供完整的 log（截图的信息太有限了）

**Comment by AirTaker** [comment]
cls版本应该是最新的，因为我是今天刚拉取的项目。

CTeX包我第一次build的时候失败了所以我卸载之后又重新安装了，不知道有没有问题
![image](https://user-images.githubusercontent.com/49189171/74156708-dce0bf80-4c51-11ea-87a5-c50fe8fcd84f.png)

这是完整的log：
https://github.com/AirTaker/Default/blob/master/sample-bachelor.log

**Comment by AirTaker** [comment]
@huxuan 
cls版本应该是最新的，因为我是今天刚拉取的项目。

CTeX包我第一次build的时候失败了所以我卸载之后又重新安装了，不知道有没有问题
![image](https://user-images.githubusercontent.com/49189171/74156992-70b28b80-4c52-11ea-8e6e-f2e73b6fc1c9.png)

这是完整的log：
https://github.com/AirTaker/Default/blob/master/sample-bachelor.log

**Comment by huxuan** [comment]
几个小建议需要你尝试一下

> ("C:\Users\Li Cheng\Desktop\æ¯•ä¸šè®¾è®¡\æ¯•è®¾æ¨¡æ¿\BUAAthesis-master\sample-
bachelor.tex"

试试将文件目录改为纯英文，确保没有中文和特殊字符，最好连空格也没有

> ! Undefined control sequence.
> l.159 \ctexset

这个应该是第一条错误信息，没用过 TeXStudio，最好确认下 ctex 正确安装和配置了，比如写个简单的包含 `ctexset` 的 helloworld

**Comment by AirTaker** [comment]
已解决！感谢！！
