### ISSUE TITLE
References not working

### ISSUE THREAD

**Issue by Ngbede-Joshua** [BHOSC/BUAAthesis#254]
My references come out with '?'. please see picture below. Any help?

![image](https://user-images.githubusercontent.com/42242703/77257143-779ad800-6cad-11ea-9467-053453f6e8f9.png)

**Comment by Ngbede-Joshua** [comment]
![image](https://user-images.githubusercontent.com/42242703/77257206-dbbd9c00-6cad-11ea-80ed-e529e1d7aa40.png)
 and the errors are seen above

**Comment by JosephPeng** [comment]
@huxuan @sighingnow 
Can you guys have a look about this issue?

**Comment by JosephPeng** [comment]
Hi, @Ngbede-Joshua , could post your error paragraph code, and I wish you complied your thesis project with bibtex before xelatex when you need cite references.

**Comment by Ngbede-Joshua** [comment]
Please see :
Process started

This is BibTeX, Version 0.99d (MiKTeX 2.9.6960 64-bit) The top-level auxiliary file: reference.aux I couldn't open database file data/refff.bib ---line 4 of file reference.aux : \bibdata{data/refff : } I'm skipping whatever remains of this command I found no database files---while reading file reference.aux I found no \bibstyle command---while reading file reference.aux (There were 3 error messages)

Process exited with error(s)

**Comment by JosephPeng** [comment]
Hi, @Ngbede-Joshua 
I don't know what lead to this error, [https://github.com/BHOSC/BUAAthesis/blob/daf5a0828934fbed6f1158b0640255e72c737624/data/chapter5-usage.tex#L75](here) illustrated the usage of reference. 
you may refer to the  [https://github.com/BHOSC/BUAAthesis/blob/master/data/bibs.bib](.bib) file structure, and use the .bst file in the BUAAthesis template, and use command '\cite[key]' or '\upcite[key]' in your thesis.

**Comment by JosephPeng** [comment]
Close this issue as it has been solved.
