### ISSUE TITLE
参考文献引用，格式不正确

### ISSUE THREAD

**Issue by Lucksong** [BHOSC/BUAAthesis#257]
我clone下代码后，编译运行得到的引用文献的格式不正确。
<img width="878" alt="截屏2020-09-12 下午9 48 15" src="https://user-images.githubusercontent.com/20484903/92996897-ac436a00-f541-11ea-9883-54d8125caebb.png">
代码如下：

\texttt{.bib}参考文献数据库文件中，每个类别后的第一个为标号，在示例的\texttt{bibs.bib}中第一个书箱的标号为\textbf{kottwitz2011latex}，在引用此文献时，使用\verb|\upcite{kottwitz2011latex}|即可得到此文献\upcite{kottwitz2011latex}的引用\footnote{左侧“文献”的右上方即得到了此文献的引用。}。
使用\verb|\cite{kottwitz2011latex}|即可得到文献\cite{kottwitz2011latex}的引用\footnote{“文献”的后面得到了此文献的引用，不是上标形式。}。

**Comment by Lucksong** [comment]
![Uploading image.png…]()

**Comment by exgphe** [comment]
gbt7714的引用样式要选numerical而不是author-date

**Comment by sighingnow** [comment]
Close as answered.
