### ISSUE TITLE
参考文献的作者仍然是全部大写

### ISSUE THREAD

**Issue by Cyboteen** [BHOSC/BUAAthesis#260]
官方文档bib文件里条目的author域有带{}和不带{}的，sample里的参考文献都能以首字母大写、其他字母小写的形式输出。
但在我本地，仅author域将名字用{}标注的条目能正常显示，其他条目的作者姓氏都是大写。
请问是什么问题呢？

非常感谢！

**Comment by liueddd** [comment]
2015年新国标，要求作者姓氏全大写，名首字母大写。应该没问题。

**Comment by Cyboteen** [comment]
> 2015年新国标，要求作者姓氏全大写，名首字母大写。应该没问题。

《北京航空航天大学研究生撰写学位论文的规定》（2020年7月修订）给的示例是这样的：
`[1]毛峡, 丁玉宽．    图像的情感特征分析及其和谐感评价[J] ．电子学报, 2001, 29(12A) : 1923-1927
[2]Ozgokmen T. M., Johns W. E., Peters H., et al. Turbulent Mixing in the Red Sea Outflow Plume from a High-Resoluting Nonhydrostatic Model[J]. Jounal of Physical Oceangraphy, 2003,V33(8):1846-1869
`

修改bst文件解决了这个问题。

**Comment by sighingnow** [comment]
I think this issue requires being double check and possible fixes, as the template is not exactly same with GBT.

**Comment by Henning742** [comment]
之前给学位办打过电话，对方回复是以北航样板或以国标为准都可以，最好以北航为准。

**Comment by sighingnow** [comment]
Closed as won't be a problem, IMO.

**Comment by cpfy** [comment]
亲测可以通过修改 gbt7714-xxx.bst 文件解决，在文件中找到 `#1 'uppercase.name :=` ，修改为 `#0 'uppercase.name :=` 即可。
