### ISSUE TITLE
更新texlive 2021之后报错'Extra }, or forgotten endgroup. [ maketitlepage]'(修改\uline命令后解决)

### ISSUE THREAD

**Issue by liangyubuaa** [BHOSC/BUAAthesis#262]
怀疑是\uline命令在更新之后不支持大括号的参数命令，从而导致\hspace 的问题, 需要将 \hsapce 装在盒子里。

尝试将buaathesis.cls中包含在 \uline 中的\hspace{xxx}, 修改为 \mbox{\hspace{xxx}}，解决问题。

* 参考 https://wenda.latexstudio.net/q-5448.html
* 参考 https://blog.csdn.net/qq_41437512/article/details/114067479
* 参考 TEX.SE 上的问题 https://tex.stackexchange.com/questions/568732/uline-does-not-work-with-hspace

**Comment by sighingnow** [comment]
@liangyubuaa,

Thanks for reporting. Could you please help me confirm if #263 fixes the problem in your environment?

**Comment by liangyubuaa** [comment]
> @liangyubuaa,
> 
> Thanks for reporting. Could you please help me confirm if #263 fixes the problem in your environment?

Sure. I made the same change and the problem was fixed perfectly 

btw, some commands also seem to have compatibility issues (e.g. `\verb` from line 93-94 in chapter2-config.tex) and the error message is ` LaTeX Error: \verb ended by end of line.`. You may refer to this site [https://blog.csdn.net/xovee/article/details/106728213](url)

It is just a kind reminder, because this problem is only present in the example chapter, and it doesn't bother me at all.

**Comment by sighingnow** [comment]
Thanks for letting me know that. I will merge #263 first and check the `\verb` issue later.

**Comment by sighingnow** [comment]
@liangyubuaa FYI: the `\verb` issue has been fixed in #266, by @Chen-Jie-EE.

**Comment by sighingnow** [comment]
Hi @liangyubuaa,

For TeXLive 2021 users, I believe you need to take a look at #265, which makes an erronous format with TeXLive 2021 and has been fixed in master now.
