### ISSUE TITLE
The body content is shifted upward, conflicting with the header

### ISSUE THREAD

**Issue by tqnwhz** [BHOSC/BUAAthesis#265]
I am using the latest master code, macTex 2021 and confronted with the following problem.

![image](https://user-images.githubusercontent.com/39870399/114855621-c0718180-9e18-11eb-94dc-d3e171bbb740.png)
![image](https://user-images.githubusercontent.com/39870399/114855650-c5363580-9e18-11eb-9bb4-7047da3ffd5e.png)

**Comment by tqnwhz** [comment]
By the way, I compile it just by run the `make` command.
I am wondering whether it's a macText version incompatible error or something else, and how to resolve it .

**Comment by sighingnow** [comment]
> By the way, I compile it just by running the `make` command.
> I am wondering whether it's a macText version incompatible error or something else, and how to resolve it .
> Any help is appreciated. Thanks very much!

May I know your MacTex version? Then I could try to reproduce.

**Comment by tqnwhz** [comment]
> it .

My MacTex version is 3.141592653-2.6-1.40.22 (TeX Live 2021).
I downloaded it just yesterday, and it's supposed to be the latest version.

**Comment by tqnwhz** [comment]
> > By the way, I compile it just by running the `make` command.
> > I am wondering whether it's a macText version incompatible error or something else, and how to resolve it .
> > Any help is appreciated. Thanks very much!
> 
> May I know your MacTex version? Then I could try to reproduce.



> > By the way, I compile it just by running the `make` command.
> > I am wondering whether it's a macText version incompatible error or something else, and how to resolve it .
> > Any help is appreciated. Thanks very much!
> 
> May I know your MacTex version? Then I could try to reproduce.

My MacTex version is 3.141592653-2.6-1.40.22 (TeX Live 2021).
I downloaded it just yesterday, and it's supposed to be the latest version.

**Comment by sighingnow** [comment]
> My MacTex version is 3.141592653-2.6-1.40.22 (TeX Live 2021).
> I downloaded it just yesterday, and it's supposed to be the latest version.

Thanks.

I could reproduce the error on Mac, with TeXLive 2021. Working on that.

**Comment by sighingnow** [comment]
Hi @tqnwhz,

It should have been fixed by #265, feel free to reopen if you still encounter the same error.
