### ISSUE TITLE
Wrong number of lines in task book template

### ISSUE THREAD

**Issue by tqnwhz** [BHOSC/BUAAthesis#270]
I'm using the latest master code, texlive 2021 on windows , and confronted the following problem-the number of lines don't match:
![367d3c7d052492d294ba130f8cc86d0](https://user-images.githubusercontent.com/39870399/117236797-0c35aa80-ae5c-11eb-80da-4f2cfac7a270.png)
![e66de4fd2d289764ada01a5af7968ce](https://user-images.githubusercontent.com/39870399/117236805-1061c800-ae5c-11eb-98d0-5681189f3157.png)

while sample-bachelor.pdf looks like normally:

![image](https://user-images.githubusercontent.com/39870399/117236892-43a45700-ae5c-11eb-8c55-054977362792.png)

**Comment by sighingnow** [comment]
Thanks for providing such information, will investigate soon.

**Comment by sighingnow** [comment]
It was caused by https://github.com/BHOSC/BUAAthesis/pull/233.

**Comment by sighingnow** [comment]
Hi @tqnwhz @hsiangyuzhao, could you guys help me to verify if #271 fixes your problem?

Thanks~

**Comment by tqnwhz** [comment]
> Hi @tqnwhz @hsiangyuzhao, could you guys help me to verify if #271 fixes your problem?
> 
> Thanks~

It seems to solve the problem. Thanks !

**Comment by hsiangyuzhao** [comment]
> Hi @tqnwhz @hsiangyuzhao, could you guys help me to verify if #271 fixes your problem?
> 
> Thanks~

Problem solved! Really appreciate your help and efforts!
