### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by nekithockey75** [BHOSC/BUAAthesis#272]
Hello!

Running `make master` causes the following error. 

```
(d:/Programs/texlive/2021/texmf-dist/tex/latex/fancyhdr/fancyhdr.sty))
! Incomplete \iffalse; all text was ignored after line 128.
<inserted text>
                \fi
l.3

?
```

I haven't modified the code.

How to reproduce:

 1. Windows 10
 2. Latex version: `XeTeX 3.141592653-2.6-0.999993 (TeX Live 2021/W32TeX) kpathsea version 6.3.3`
 3. Run `make master`

**Comment by huxuan** [comment]
应该是由于fancyhdr升级导致的，之前有过一次hack，但是看来又升级了 - -

可以先把 buaathesis.cls 里的 128行-131行删掉试一下 [1]

```
\ifbuaa@bachelor
    \newif\iff@nch@compatViii
    \let\f@nch@gbl\relax
    \let\f@nch@gbl\global
        \f@nch@compatViiitrue
\fi
```

[1] https://github.com/BHOSC/BUAAthesis/blob/b085bb0438d3493e5465a9f4862ccbfff6c85ff7/buaathesis.cls#L128

**Comment by CookieLau** [comment]
Bachelor 编译也会遇到问题，注释 buaathesis.cls 的第 130 行即可解决问题。 
`130: \f@nch@compatViiitrue`

**Comment by sighingnow** [comment]
> Bachelor 编译也会遇到问题，注释 buaathesis.cls 的第 130 行即可解决问题。
> `130: \f@nch@compatViiitrue`

也是TexLive 2021 on Windows么

**Comment by CookieLau** [comment]
> > Bachelor 编译也会遇到问题，注释 buaathesis.cls 的第 130 行即可解决问题。
> > `130: \f@nch@compatViiitrue`
> 
> 也是TexLive 2021 on Windows么

TeX 3.14159265 (TeX Live 2020) MacOS + VSCode 1.56.0 + james-yu.latex-workshop 插件

**Comment by huxuan** [comment]
> > > Bachelor 编译也会遇到问题，注释 buaathesis.cls 的第 130 行即可解决问题。
> > > `130: \f@nch@compatViiitrue`
> > 
> > 
> > 也是TexLive 2021 on Windows么
> 
> TeX 3.14159265 (TeX Live 2020) MacOS + VSCode 1.56.0 + james-yu.latex-workshop 插件

最新版还会有吗？我这是2021没法复现的说……

**Comment by sighingnow** [comment]
> > > Bachelor 编译也会遇到问题，注释 buaathesis.cls 的第 130 行即可解决问题。
> > > `130: \f@nch@compatViiitrue`
> > 
> > 
> > 也是TexLive 2021 on Windows么
> 
> TeX 3.14159265 (TeX Live 2020) MacOS + VSCode 1.56.0 + james-yu.latex-workshop 插件

hi @CookieLau,

Could you help us if #276 works for your environment?
