### ISSUE TITLE
硕士模板在TexLive2020编译序错误

### ISSUE THREAD

**Issue by CuiiGen** [BHOSC/BUAAthesis#275]
硕士模板在TexLive2020环境下报错，但master模板不会，报错提示如为：
```
Undefined control sequence.
    \f@nch@compatViiitrue
LaTeX
```
报错位置为：
https://github.com/BHOSC/BUAAthesis/blob/88137140605eab55b9cb56d3fd4bba7e875c4fee/buaathesis.cls#L130

**Comment by huxuan** [comment]
硕士模板 和 master 模板？是不是typo了

我本地升级了2021是没有问题的，建议升级一下。

**Comment by CuiiGen** [comment]
是sample-bachelor.tex编译报错，sample-master.tex则没问题

**Comment by sighingnow** [comment]
Hi @CuiiGen,

Could you help us if #276 works for your environment?

**Comment by CuiiGen** [comment]
问题解决了 @sighingnow

**Comment by sighingnow** [comment]
Thanks. I'm going to land it.
