### ISSUE TITLE
链接过期

### ISSUE THREAD

**Issue by soldivelot** [BHOSC/BUAAthesis#283]
https://github.com/BHOSC/BUAAthesis/blob/d693517032859e956509496b2f9c92eda8354094/data/com_info.tex#L5
原来的打不开了，应该是这个：
http://www.buaa.edu.cn/jgsz/yxsz.htm

**Comment by sighingnow** [comment]
Thanks for reporting! Would you mind to submit a pull request for a quickfix? Thanks!

**Comment by sighingnow** [comment]
Closed by #284.
