### ISSUE TITLE
关于开题报告/综述部分的重构想法

### ISSUE THREAD

**Issue by HansBug** [BHOSC/BUAAthesis#289]
Hi, gentlemen. Nice to meet you all, it's my pleas..... 咳咳好尬，总之很高兴能在这卷王时代，在程序猿们的真正家园遇到同志，哈哈。

说正事，我刚研究了一下之前开题报告的pr代码，功能基本ok但是缝合感明显。我认为主要问题出在这里——实际上开题/综述之类的东西是与本科/硕士/博士这一学位变量无关的，是另一个维度上的存在，而在`buaathesis.cls` 中， #258 这个pr的实现却将开题/综述与学位放在了并行位置上，于是就容易有问题，比如和`twoside`是不兼容的。

这部分我倒是感觉比较理想的一个状态是能将`kaitireport`或者`review`摆在documentclass那里。

当然了，考虑到实际使用需要，建议这波pr #287 还是尽快merge起来，然后重构后续再来弄。

BTW，接个其他人留下来的pr整起来好难受 😢 。

**Comment by sighingnow** [comment]
#287那几个comments address之后就可以合并了

> 这部分我倒是感觉比较理想的一个状态是能将kaitireport或者review摆在documentclass那里。

没问题的~

**Comment by soldivelot** [comment]
确实需要重新设计一下，现在代码包括文件的分类都是针对毕业论文设计的，在毕业论文的前提下对学位进行分类，直接加入开题报告就会比较奇怪，比如作者中英文名什么的那些信息就只能放在主文件下，没法拆出来

**Comment by HansBug** [comment]
Merged in #296 .
