### ISSUE TITLE
学术型和专业型学位，封面、提名页的不同之处

### ISSUE THREAD

**Issue by xuefeng-xu** [BHOSC/BUAAthesis#291]
学术博士vs专业博士
![image](https://user-images.githubusercontent.com/41134380/144535248-631631b3-7b59-4319-b236-f2e7743912fc.png)
![image](https://user-images.githubusercontent.com/41134380/144535186-0f918d7e-592c-4d13-a915-bdaaa1be25d7.png)
学术硕士vs专业硕士
![image](https://user-images.githubusercontent.com/41134380/144535126-c6b3b143-e155-4d34-8bee-30d7e8b3c8ef.png)
![image](https://user-images.githubusercontent.com/41134380/144535327-d5b4b2b9-de07-446a-99b0-30cb48e79a15.png)

[http://graduate.buaa.edu.cn/info/1039/7831.htm](http://graduate.buaa.edu.cn/info/1039/7831.htm)

**Comment by soldivelot** [comment]
[#288](https://github.com/BHOSC/BUAAthesis/pull/288)里有修改，你可以更新下看看解决没有

**Comment by xuefeng-xu** [comment]
已经解决，谢谢，添加professional即可
![image](https://user-images.githubusercontent.com/41134380/144608242-efcc809b-51d1-41da-9f8e-5bad8b7aabd2.png)
