### ISSUE TITLE
关于可能存在的字体缺少问题

### ISSUE THREAD

**Issue by HansBug** [BHOSC/BUAAthesis#294]
刚才这边经过测试，在linux环境下编译不通过的主要原因在于缺少字体（例如`Times New Roman`等）

请问各位对这个问题有何建议？是否该考虑将一些主要的字体文件加入到仓库中，并在README中加入相关安装指引？

btw: 这边正在尝试给仓库添加github action，让其能自动编译运行，因此也正在进行逐个排雷中，等CI那边能全部过编译了应该也就能将主要问题都总结出来了。

**Comment by sighingnow** [comment]
> 

CI 的问题在于装texlive太慢了。。（好几年前在travis-ci上尝试build过另一个project）。

> 是否该考虑将一些主要的字体文件加入到仓库中，并在README中加入相关安装指引？

顶多给出安装指引，比如从哪里下载等等。把字体文件放进repo不太合适~

**Comment by HansBug** [comment]
@sighingnow 我这边已经弄出来靠谱的CI运行方案了，装texlive显然很慢，不过现在github-action有现成的虚拟环境可以用。

以及，在CI中运行的话，一些字体依然不太好下载（指的是用命令很自然地下载），所以有啥好的办法可以将资源上传然后供CI里面curl下载不？

**Comment by HansBug** [comment]
这样，我先开个public repo，把字体丢进去，然后CI运行的时候clone过来。

这边暂时找不到比较合适的静态资源托管服务。

**Comment by huxuan** [comment]
字体没有放进来主要是版权的原因，建议这块最好还是谨慎一点。

**Comment by HansBug** [comment]
@huxuan 

这边是这么个情况，目前主要缺：
* `Times New Roman`，这个刚确认过了，免费可商用
* `STXingKai`，刚查了一下，华文行楷商用需要授权，不过不知道我们这个算不算商用~~~，求解答

这个问题真的得能解决，不然很麻烦

**Comment by huxuan** [comment]
我们这个应该是不算商用的，印象中当初比较麻烦的就是华文行楷，Times New Roman 本身也有不少很相近的替代品，不过 anyway，这些都是比较老古董的事情了，那时候也没有 Github Actions，能搞一个也挺好的，理论上大家可以 fork 过去本地不安装 latex 也可以用了。

**Comment by HansBug** [comment]
@huxuan 

是的，尤其是github action这个东西，对外部设施依赖非常低（此处点名gitlab runner，那玩意好多都得自己配置），基本上fork即用。

字体那边我已经换上链接下载了，目前还在等review，感觉基本上ok了

**Comment by HansBug** [comment]
Closed due to #295
