### ISSUE TITLE
CI Linux环境编译与实际Win环境编译存在不同

### ISSUE THREAD

**Issue by HansBug** [BHOSC/BUAAthesis#297]
如题所示，目前已知的现象包含：
* 硕士第二页英文缺少加粗：https://github.com/BHOSC/BUAAthesis/pull/296#issuecomment-986214488
* 数字与字母会出现原本并不存在的斜体

此问题后续有待进一步修复，疑似在这些环境下缺少相关的字体文件或定义。

**Comment by HansBug** [comment]
进一步测试了一下，很奇怪，本地ubuntu环境在装了这几个字体后，运行正常，没有出现上述问题。

**Comment by huxuan** [comment]
是不是因为没有刷新字体 cache?  `fc-cache -f -v`

可以使用 `fc-list` 来 check 一下

**Comment by HansBug** [comment]
刚去跑了一下字体识别，CI里面出来的英文和数字字体应该是Nimbus Roman Italic，不知道有没有人有头绪。

@huxuan 应该不是这个原因，action里面的latex编译虚拟环境会安装指定的那些外部字体（这个action本质上提供了一个docker虚拟环境，在内部进行的编译），然后就不知道为啥，Times New Roman出不来。

**Comment by HansBug** [comment]
CI上的完整运行日志：[7_Compile sample-master.tex to pdf.txt](https://github.com/BHOSC/BUAAthesis/files/7657687/7_Compile.sample-master.tex.to.pdf.txt)

本地的完整运行日志：[local_run_log.txt](https://github.com/BHOSC/BUAAthesis/files/7657689/local_run_log.txt)

简单对比了一下，CI里面有大量类似这样的warning：

```
2021-12-05T12:48:49.9994119Z LaTeX Font Warning: Font shape `TU/TimesNewRoman(0)/m/it' undefined
2021-12-05T12:48:49.9994930Z (Font)              using `TU/TimesNewRoman(0)/m/sl' instead on input line 203.
```
