### ISSUE TITLE
Color of cite and TOC

### ISSUE THREAD

**Issue by HansBug** [BHOSC/BUAAthesis#300]
如题，目前footnote、ref以及目录均为红色，而cite为绿色。

请问这是有什么特殊的规定吗？目前我所接触到的都统一用的黑色。

求各位前辈解答。如果这部分有必要调整的话后续会考虑开个pr。

**Comment by sighingnow** [comment]
There's an option that controls the behaviour: https://github.com/BHOSC/BUAAthesis/blob/master/data/chapter5-usage.tex#L53

**Comment by sighingnow** [comment]
Close as answered.

**Comment by HansBug** [comment]
Okay, got it.

Actually, the format requirements of all the degree's paper are non-colored.

**Comment by huxuan** [comment]
> Okay, got it.
> 
> Actually, the format requirements of all the degree's paper are non-colored.

Generally, color is useful in the electronic edition, providing an option for color is kind of convention.
