### ISSUE TITLE
参考文献国标

### ISSUE THREAD

**Issue by xinwen-cs** [BHOSC/BUAAthesis#301]
图书馆提交要求使用87版国标，为啥对应的bst文件被移除了，2015版能通过图书馆审核吗？

**Comment by sighingnow** [comment]
See https://github.com/BHOSC/BUAAthesis/pull/255

**Comment by sighingnow** [comment]
I think it should be to OK to use gbt7714-2015.

I haven't compared the differences between those versions, but the original bst is for gbt7714-05, and I have never known there are issues when submiting the final version.
