### ISSUE TITLE
Plantuml supported version.

### ISSUE THREAD

**Issue by HansBug** [BHOSC/BUAAthesis#303]
写硕士开题期间搓了一个支持plantuml自动编译的版本：https://github.com/HansBug/BUAAthesis/tree/dev/diagrams

Q: 为啥不用plantuml package
A: 生成图效果实在不咋样，还有latex环境上的外部依赖，不利于自动化。还是makefile编译产生eps再装进pdf香，简单暴力管用。

不知道几位是否有兴趣，这种图很适合用来绘制流程、系统架构、状态等，而且只需要改改代码即可在repo里维护。

btw: graphviz我也在这次用到，不过似乎中文支持有点小毛病所以暂时没放进来，后续我研究下怎么搞，对6系人这玩意很重要，画数据结构必备。

**Comment by HansBug** [comment]
以及实际上脑洞可以开的更大一些，比如支持通用的`sh`脚本，这种东西挺适合拿来自动生成文档里面的图，以及程序片段运行结果的。

**Comment by sighingnow** [comment]
Not everyone needs such diagram support and I think `plantuml` doesn't fit the need of everyone who needs diagrams, based on user preferences.

I'm OK to add a section about how to adding support of plantuml to the document (as we already have many "how-to-use" sections), but I prefer not adding it to the default settings.

**Comment by sighingnow** [comment]
Maybe adding to https://github.com/BHOSC/BUAAthesis/blob/master/data/chapter4-basic.tex would be enough?

**Comment by HansBug** [comment]
Well, may be just put it into a branch? And put a guide section to the main branch's version?

**Comment by sighingnow** [comment]
Generating svg/pdf from `.dot` file and related Makefile targets shouldn't be part of the template repo. Imaging that I don't have some `.dot` file, but have some `.py` files that generate `.dot` files then generate pdf using graphviz. Then what I need in the Makefile would be running `python` rather than `dot`.

I mean, it is a very customized feature that depends on user experience and not suitable for a "Template" project.

**Comment by sighingnow** [comment]
I'm ok with adding "How-to"s for such highly customized feature requests, but I prefer to keep the template "clean" and keep it as just a "template".

**Comment by HansBug** [comment]
Okay, I see, I will keep this.version in my fork repo. And maybe create standalone project for this kind of feature(actually it is not only useful in latex building).

**Comment by HansBug** [comment]
- [Version with PlantUML](https://github.com/HansBug/BUAAthesis/tree/dev/diagrams)
- [Version with PlantUML && Graphviz](https://github.com/HansBug/BUAAthesis/tree/dev/graphviz)

Will be long-term maintained.

And when the tools which can create this feature [mentioned here](https://github.com/BHOSC/BUAAthesis/issues/303#issuecomment-996497214), I will append a comment.

**Comment by sighingnow** [comment]
Closed as discussed.
