### ISSUE TITLE
开题报告封面姓名问题

### ISSUE THREAD

**Issue by VoyagerCoder** [BHOSC/BUAAthesis#306]
开题报告的姓名那行似乎应该是“姓名”，不是“本科生”？

**Comment by sighingnow** [comment]
![image](https://user-images.githubusercontent.com/7144772/154389012-9bb8d48a-ebc9-408f-a5f7-8c2aa40df542.png)

现在本科生论文封面是这样的（master branch），问题中具体指的哪里呀？

**Comment by VoyagerCoder** [comment]
在模板文件[buaathesis.cls](https://github.com/BHOSC/BUAAthesis/blob/master/buaathesis.cls)里面
![5332686a43b7d51f8eb20652dab425c](https://user-images.githubusercontent.com/82797085/154393469-d164d252-de2f-46ef-9550-aef0d8508d63.png)
两处地方似乎应该是“姓名”
文档对应位置：
![e3eb8648bf240e0adeaa5f82006708b](https://user-images.githubusercontent.com/82797085/154394114-8b4588e2-acb9-4861-ad08-51eef20187da.png)

**Comment by sighingnow** [comment]
I see.
