### ISSUE TITLE
请问如何取消参考文献中的大小写锁定

### ISSUE THREAD

**Issue by gyp2847399255** [BHOSC/BUAAthesis#313]
![image](https://user-images.githubusercontent.com/68111555/174766923-9a27315c-2d23-4eb2-a74b-cbedac7162d7.png)

类似于这里，我希望 TCP 字母都是大写。

另外，我还希望能删掉后面的 `[S.1.]:`，请问我该如何修改

**Comment by Idolphint** [comment]
所以怎么删掉后面的[S.l.]呢
