### ISSUE TITLE
更好的PDF转Word工具

### ISSUE THREAD

**Issue by DYY-Drummer** [BHOSC/BUAAthesis#317]
https://www.ilovepdf.com/

这个网站免费的，比现在提供的两个网站都好用多了，几乎没有任何混乱，甚至是页眉和页脚

**Comment by Mingzefei** [comment]
把论文上传到网络有风险，需要留意。
另外，可使用 pandoc 将 tex 直接换成 docx，具体可以参考 [这篇blog](http://mingzf.xyz/zh-cn/posts/latex2word/)。
