### ISSUE TITLE
请问如何删掉每章后边空白页，导师让全删掉

### ISSUE THREAD

**Issue by SwordHolderSH** [BHOSC/BUAAthesis#324]
请问如何删掉每章后边空白页，以及所有空白页，导师让全删掉

**Comment by SwordHolderSH** [comment]
好的，会了

改成
` \documentclass[doctor,oneside,win]{buaa}`
就行了

**Comment by songjinghe** [comment]
我是开始没有后来审稿人让加上😂。这不是章后的空白页，而是章前的空白页，因为学位论文有要求“每章必须从奇数页开头”，所以不足奇数页的会补一页。加上`openright`就行了
