### ISSUE TITLE
bib file

### ISSUE THREAD

**Issue by huxuan** [BHOSC/BUAAthesis#66]
- example of different types
- add reference of material or other repos used in documentation

**Comment by Ngbede-Joshua** [comment]
Hello, 
Please I need to know how to reference on the template. I used  \cite{} and  \citep{} and both are not working.
Also, do you have the template in English? at the moment I am using the Chinese template provided.
 Thank you!

**Comment by sighingnow** [comment]
> Also, do you have the template in English?

No english version available since the users would be asked to submit the Chinese version, AFAIK.

**Comment by sighingnow** [comment]
Close as we have moved to gbt7714.sty and we have another issue #252 to track the sync problem.
